#!/usr/bin/env python3
"""Checks and a figure for 'The tower of lattices' (notes/adelic-gkp/lattice-tower.md).

Setting. L = Z^{2n} with the standard symplectic form Omega (the stabiliser lattice of n GKP qunaught modes).
A step is an integer matrix M with M^T Omega M = q Omega; V = q M^{-1} is its Omega-adjoint, MV = VM = q.
For a graph with flux, M = [[0, -1], [q, A_s]] (graph-super.md).
Point tower: L_k = (1 - V^k) L; the code with stabiliser lattice L_k has dimension h_k = det(1 - M^k) and basis
W(e)|L>, e in Fix(M^k) = (1 - M^k)^{-1} L / L (the syndromes of period k).
Kernel tower: M^k L, of index q^{nk}.
"""
import os
import itertools
from fractions import Fraction
from math import gcd
import numpy as np
import sympy as sp
from sympy.matrices.normalforms import smith_normal_form
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
NOTE = os.path.dirname(HERE)
npass = nfail = 0


def check(name, ok, detail=""):
    global npass, nfail
    npass += bool(ok)
    nfail += (not ok)
    print(("PASS  " if ok else "FAIL  ") + name + ("  " + detail if detail else ""))


def obj(M):
    return np.array(M, dtype=object)

def mpow(M, k):
    P = np.eye(len(M), dtype=object)
    for _ in range(k):
        P = P.dot(M)
    return P

def omega(n):
    I, Z = np.eye(n, dtype=object), np.zeros((n, n), dtype=object)
    return np.block([[Z, I], [-I, Z]])

def step(As, q):
    n = len(As)
    I, Z = np.eye(n, dtype=object), np.zeros((n, n), dtype=object)
    return np.block([[Z, -I], [q * I, obj(As)]])

def det_int(M):
    return int(sp.Matrix(M.tolist()).det())

def invariants(M):
    S = smith_normal_form(sp.Matrix(M.tolist()), domain=sp.ZZ)
    return sorted(abs(int(S[i, i])) for i in range(len(M)) if abs(int(S[i, i])) != 1)

def frac_mod1(v):
    return tuple(Fraction(x) - (Fraction(x).numerator // Fraction(x).denominator) for x in v)

def periodic_points(M, k):
    """Fix(M^k) on R^{2n}/Z^{2n} as a list of tuples of Fractions (the group generated by the columns of (1-M^k)^{-1})"""
    C = sp.Matrix((np.eye(len(M), dtype=object) - mpow(M, k)).tolist())
    Ci = C.inv()
    gens = [frac_mod1([Fraction(int(sp.numer(Ci[i, j])), int(sp.denom(Ci[i, j]))) for i in range(len(M))]) for j in range(len(M))]
    zero = tuple(Fraction(0) for _ in range(len(M)))
    seen, frontier = {zero}, [zero]
    while frontier:
        new = []
        for e in frontier:
            for g in gens:
                f = frac_mod1([a + b for a, b in zip(e, g)])
                if f not in seen:
                    seen.add(f)
                    new.append(f)
        frontier = new
    return sorted(seen)

def act(M, e):
    return frac_mod1([sum(Fraction(int(M[i, j])) * e[j] for j in range(len(e))) for i in range(len(e))])

def pair(Om, lam, e):
    """Omega(lam, e) mod 1"""
    v = sum(Fraction(int(lam[i])) * Fraction(int(Om[i, j])) * e[j] for i in range(len(e)) for j in range(len(e)))
    return v - (v.numerator // v.denominator)


A4 = np.ones((4, 4), dtype=int) - np.eye(4, dtype=int)
A4s = A4.copy()
A4s[0, 1] = A4s[1, 0] = -1
EX = {
    "E mode (lambda=-1, q=2)": (obj([[0, -1], [2, -1]]), 2),
    "Pauli six (lambda=-2, q=5)": (obj([[0, -1], [5, -2]]), 5),
    "K4, one negative edge (q=2)": (step(A4s, 2), 2),
    "hyperbolic step (lambda=5, q=5)": (obj([[0, -1], [5, 5]]), 5),
}

# ------------------------------------------------------------------------------------------ W1
print("== W1  the step and its adjoint")
for name, (M, q) in EX.items():
    n = len(M) // 2
    Om = omega(n)
    Mi = sp.Matrix(M.tolist()).inv()
    V = obj((q * Mi).tolist())
    okint = all(sp.Integer(x) == x for x in (q * Mi))
    V = np.array([[int(x) for x in row] for row in V.tolist()], dtype=object)
    EX[name] = (M, q, V, Om)
    check(f"{name}: M^T Omega M = q Omega; V = q M^-1 is integral and is the Omega-adjoint of M",
          np.array_equal(M.T.dot(Om).dot(M), q * Om) and okint and np.array_equal(Om.dot(V), M.T.dot(Om)))

# ------------------------------------------------------------------------------------------ W2-W4
print("== W2  the point tower: codes, nesting, the Galois permutation")
KMAX = {"E mode (lambda=-1, q=2)": 8, "Pauli six (lambda=-2, q=5)": 4, "K4, one negative edge (q=2)": 3, "hyperbolic step (lambda=5, q=5)": 5}
PTS = {}
for name, (M, q, V, Om) in EX.items():
    n = len(M) // 2
    I = np.eye(2 * n, dtype=object)
    hs, table = [], []
    for k in range(1, KMAX[name] + 1):
        h = det_int(I - mpow(M, k))
        P = periodic_points(M, k)
        PTS[(name, k)] = P
        hs.append(h)
        okk = len(P) == abs(h) and det_int(I - mpow(V, k)) == h
        # every periodic syndrome is fixed by the stabilisers of L_k = (1 - V^k) L: Omega((1-V^k) y, e) in Z
        Lk = I - mpow(V, k)
        okk &= all(pair(Om, Lk[:, j], e) == 0 for j in range(2 * n) for e in P[:200])
        # Galois permutation e -> M e
        Pset = set(P)
        img = [act(M, e) for e in P]
        okk &= set(img) == Pset
        idx = {e: i for i, e in enumerate(P)}
        perm = [idx[f] for f in img]
        seen, orbits = set(), {}
        for i in range(len(P)):
            if i not in seen:
                j, size = i, 0
                while j not in seen:
                    seen.add(j)
                    j = perm[j]
                    size += 1
                orbits[size] = orbits.get(size, 0) + 1
        okk &= all(k % d == 0 for d in orbits)
        table.append((k, h, invariants(I - mpow(M, k)), dict(sorted(orbits.items()))))
        if not okk:
            check(f"{name}: level {k}", False)
    check(f"{name}: #Fix(M^k) = det(1 - M^k) = dim of the code with stabiliser lattice (1 - V^k)L; M permutes Fix(M^k); orbit sizes divide k", True,
          f"h_k = {hs}")
    for k, h, inv, orb in table:
        print(f"      k = {k}: h = {h}, group invariants {inv}, orbits of the step (size: number) {orb}")
    ok = all(set(PTS[(name, d)]) <= set(PTS[(name, k)]) for k in range(1, KMAX[name] + 1) for d in range(1, k) if k % d == 0)
    check(f"{name}: nesting Fix(M^d) < Fix(M^k) for d | k", ok)
    k = KMAX[name] if name != "E mode (lambda=-1, q=2)" else 6
    P = PTS[(name, k)]
    idx = {e: i for i, e in enumerate(P)}
    perm = [idx[act(M, e)] for e in P]
    cur, okt = list(range(len(P))), True
    for j in range(1, k + 1):
        cur = [perm[c] for c in cur]
        fixed = sum(1 for i, c in enumerate(cur) if i == c)
        okt &= fixed == abs(det_int(I - mpow(M, gcd(j, k))))
    check(f"{name}: Tr(Phi^j on the level-{k} code) = h_gcd(j,k) for j = 1..{k}", okt)

# ------------------------------------------------------------------------------------------ W5
print("== W5  logical operators of the level-k code: a Heisenberg group, and the step as a logical Clifford")
for name, k in (("E mode (lambda=-1, q=2)", 4), ("E mode (lambda=-1, q=2)", 5), ("Pauli six (lambda=-2, q=5)", 2), ("K4, one negative edge (q=2)", 1)):
    M, q, V, Om = EX[name]
    n2 = len(M)
    P = PTS[(name, k)]
    h = len(P)
    idx = {e: i for i, e in enumerate(P)}
    basis = [np.eye(n2, dtype=object)[:, j] for j in range(n2)]
    chars = {j: tuple(pair(Om, basis[j], e) for e in P) for j in range(n2)}
    # the characters generated by the stabilisers of L: closure under addition
    zero = tuple(Fraction(0) for _ in P)
    seen, frontier = {zero}, [zero]
    while frontier:
        new = []
        for c in frontier:
            for j in range(n2):
                d = tuple((a + b) - ((a + b).numerator // (a + b).denominator) for a, b in zip(c, chars[j]))
                if d not in seen:
                    seen.add(d)
                    new.append(d)
        frontier = new
    cols = {tuple(chars[j][i] for j in range(n2)) for i in range(h)}
    ok = len(seen) == h and len(cols) == h
    # commutation: translating by f multiplies Z_lambda by exp(2 pi i Omega(lambda, f))
    f = P[min(3, h - 1)]
    shift = [idx[frac_mod1([a + b for a, b in zip(e, f)])] for e in P]
    for j in range(n2):
        ph = pair(Om, basis[j], f)
        ok &= all((chars[j][shift[i]] - chars[j][i] - ph) % 1 == 0 for i in range(h))
    # the step: Phi Z_lambda Phi^-1 = Z_{V^(k-1) lambda}, and the pairing is preserved
    Vk1 = mpow(V, k - 1)
    Minv_pts = {e: act(mpow(M, k - 1), e) for e in P}
    for j in range(n2):
        lam2 = Vk1[:, j]
        ok &= all(pair(Om, basis[j], Minv_pts[e]) == pair(Om, lam2, e) for e in P)
    check(f"{name}, level {k}: {h} characters separate the {h} points (irreducible Heisenberg representation); X Z = phase Z X; "
          f"the step maps Z_lambda to Z_(V^-1 lambda) and X_e to X_(Me), preserving the pairing", ok)

# ------------------------------------------------------------------------------------------ W6
print("== W6  the kernel tower M^k L and the comparison of the two towers")
for name, (M, q, V, Om) in EX.items():
    n = len(M) // 2
    I = np.eye(2 * n, dtype=object)
    rows = []
    ok = True
    for k in range(1, 7):
        Mk = mpow(M, k)
        ok &= abs(det_int(Mk)) == q ** (n * k)
        h = det_int(I - Mk)
        rows.append((k, h, q ** (n * k), h / q ** (n * k)))
    inv = invariants(mpow(M, 3))
    check(f"{name}: [L : M^k L] = q^(nk)", ok, f"L / M^3 L has invariants {inv}")
    mu = np.linalg.eigvals(np.array(M, dtype=float))
    ram = bool(np.allclose(np.abs(mu), np.sqrt(q)))
    bound_ok = all(abs(r[3] - 1) <= (1 + q ** (-r[0] / 2)) ** (2 * n) - 1 + 1e-12 for r in rows)
    print(f"      all |mu| = sqrt q: {ram};  h_k / q^(nk) for k = 1..6: {[round(r[3], 4) for r in rows]};  within (1 + q^(-k/2))^(2n) - 1: {bound_ok}")
    if "hyperbolic" in name:
        check(f"{name}: the ratio h_k / q^(nk) leaves the Weil window", not bound_ok)
    else:
        check(f"{name}: |h_k / q^(nk) - 1| <= (1 + q^(-k/2))^(2n) - 1 for k = 1..6", bound_ok)

# ------------------------------------------------------------------------------------------ W7
print("== W7  the invariant vacuum, oscillator frequencies, and the shape of the lattice")
def sqrtm_sym(Bm):
    w, U = np.linalg.eigh(Bm)
    return U @ np.diag(np.sqrt(w)) @ U.T
for name, (M, q, V, Om) in EX.items():
    n = len(M) // 2
    Mf, Omf = np.array(M, dtype=float), np.array(Om, dtype=float)
    S = Mf / np.sqrt(q)
    G = 0.5 * Omf @ (Mf - np.array(V, dtype=float))        # the Weil form: Omega (M - V) / 2
    evG = np.linalg.eigvalsh((G + G.T) / 2)
    if "hyperbolic" in name:
        check(f"{name}: the Weil form is indefinite and S has an eigenvalue off the unit circle (no invariant vacuum)",
              evG.min() < 0 < evG.max() and not np.allclose(np.abs(np.linalg.eigvals(S)), 1), f"eigenvalues of S: {np.round(np.sort(np.abs(np.linalg.eigvals(S))), 4)}")
        continue
    ok = np.allclose(G, G.T) and evG.min() > 0 and np.allclose(S.T @ G @ S, G)
    # compatible complex structure: polar part of K = G^{-1} Omega^T ... use K = Omega^{-1} G, which commutes with S
    Kc = np.linalg.inv(Omf) @ G
    R = sqrtm_sym(G)
    Ri = np.linalg.inv(R)
    Ksym = R @ Kc @ Ri                                   # antisymmetric in the G-orthonormal frame
    absK = sqrtm_sym(Ksym.T @ Ksym)
    J = Ri @ (Ksym @ np.linalg.inv(absK)) @ R
    gJ = Omf @ J
    if np.linalg.eigvalsh((gJ + gJ.T) / 2).min() < 0:
        J, gJ = -J, -gJ
    ok &= np.allclose(J @ J, -np.eye(2 * n)) and np.allclose(J @ S, S @ J) and np.allclose(J.T @ Omf @ J, Omf)
    ok &= np.allclose(gJ, gJ.T) and np.linalg.eigvalsh((gJ + gJ.T) / 2).min() > 0 and np.allclose(S.T @ gJ @ S, gJ)
    sigma = 0.5 * np.linalg.inv(gJ)                        # covariance of the invariant pure Gaussian state (hbar = 1)
    ok &= np.allclose(S @ sigma @ S.T, sigma) and np.allclose((sigma @ Omf) @ (sigma @ Omf), -0.25 * np.eye(2 * n))
    ang = np.sort(np.abs(np.angle(np.linalg.eigvals(S))))
    lam = np.sort(np.linalg.eigvals(Mf + np.array(V, dtype=float)).real)[::2]
    ang2 = np.sort(np.repeat(np.arccos(lam / (2 * np.sqrt(q))), 2))
    ok &= np.allclose(ang, ang2, atol=1e-8)
    check(f"{name}: Weil form positive and S-invariant; invariant complex structure J (J^2 = -1, JS = SJ, Omega(.,J.) > 0); "
          f"invariant pure Gaussian state; normal-mode frequencies = angles of the lines", ok, f"angles/pi: {np.round(np.unique(np.round(ang, 8)) / np.pi, 4)}")
    hk_ok = all(abs(det_int(np.eye(2 * n, dtype=object) - mpow(M, k)) - np.prod(np.abs(1 - q ** (k / 2) * np.exp(1j * k * ang[::2])) ** 2)) < 1e-6 * abs(det_int(np.eye(2 * n, dtype=object) - mpow(M, k))) for k in range(1, 6))
    check(f"{name}: h_k = prod_j |1 - q^(k/2) e^(i k theta_j)|^2, k = 1..5", hk_ok)
for name in ("E mode (lambda=-1, q=2)", "Pauli six (lambda=-2, q=5)", "hyperbolic step (lambda=5, q=5)"):
    M, q, V, Om = EX[name]
    lam = int(M[1, 1])
    Q2 = np.array([[2 * q, lam], [lam, 2]])
    Gm = np.array(Om, dtype=float) @ (np.array(M, dtype=float) - np.array(V, dtype=float))
    disc = lam * lam - 4 * q
    cyc = [v for v in itertools.product(range(-2, 3), repeat=2) if abs(v[0] * (int(M[1, 0]) * v[0] + int(M[1, 1]) * v[1]) - v[1] * (int(M[0, 0]) * v[0] + int(M[0, 1]) * v[1])) == 1]
    check(f"{name}: the lattice with the invariant form is the binary quadratic form q x^2 + lambda x y + y^2 of discriminant {disc}; L is a cyclic Z[M]-module",
          np.allclose(Gm, Q2) and len(cyc) > 0, f"form ({q}, {lam}, 1); cyclic vector {cyc[0]}")

# ------------------------------------------------------------------------------------------ W8
print("== W8  Deligne's conditions (Goresky-Tai, refs/src/1701.07742/main.tex:561-572)")
for name, (M, q, V, Om) in EX.items():
    n = len(M) // 2
    x = sp.symbols("x")
    cp = sp.Poly(sp.Matrix(M.tolist()).charpoly(x).as_expr(), x)
    co = [int(c) for c in cp.all_coeffs()]
    mid = co[n]
    p = sp.factorint(q)
    p = list(p.keys())[0]
    mu = np.linalg.eigvals(np.array(M, dtype=float))
    semis = sp.Poly(sp.gcd(cp.as_expr(), sp.diff(cp.as_expr(), x)), x).degree() == 0 or sp.Matrix(M.tolist()).is_diagonalizable()
    c1 = bool(np.allclose(np.abs(mu), np.sqrt(q))) and bool(semis)
    c3 = mid % p != 0
    print(f"      {name}: char poly coefficients {co}; (1) semisimple with |mu| = sqrt q: {c1}; (3) middle coefficient {mid} prime to {p}: {c3}; (4) V exists: True")
    if "hyperbolic" in name:
        check(f"{name}: not a Deligne module (condition 1 fails)", not c1)
    else:
        check(f"{name}: a Deligne module of rank {2 * n} over F_{q}", c1 and c3)

# ------------------------------------------------------------------------------------------ W9
print("== W9  torsion syndromes split into a periodic part and a part killed by the step (E mode)")
M, q, V, Om = EX["E mode (lambda=-1, q=2)"]
Mi = np.array([[int(x) for x in row] for row in M.tolist()])
for N in (8, 24):
    pts = [np.array([a, b]) for a in range(N) for b in range(N)]
    per, nil = set(), set()
    for e in pts:
        f, seen = e.copy(), []
        for _ in range(4 * N):
            f = (Mi @ f) % N
            seen.append(tuple(f))
        if tuple(e) in seen:
            per.add(tuple(e))
        if (0, 0) in seen:
            nil.add(tuple(e))
    sums = {((a[0] + b[0]) % N, (a[1] + b[1]) % N) for a in per for b in nil}
    check(f"N = {N}: the N-torsion syndromes are (periodic) + (killed), a direct sum", len(per) * len(nil) == N * N and len(sums) == N * N and per & nil == {(0, 0)},
          f"{len(per)} periodic x {len(nil)} killed = {N * N}")

# ------------------------------------------------------------------------------------------ figure
INK, MUTED, GRID, AXIS, SURF = "#0b0b0b", "#52514e", "#e1e0d9", "#c3c2b7", "#fcfcfb"
BLUE, ORANGE = "#2a78d6", "#eb6834"
plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 10, "axes.edgecolor": AXIS, "axes.labelcolor": MUTED,
                     "xtick.color": MUTED, "ytick.color": MUTED, "figure.facecolor": SURF, "axes.facecolor": SURF, "savefig.facecolor": SURF})
print("== Figure  the lattice of the E mode in vacuum coordinates, with the two towers")
mu = (-1 + 1j * np.sqrt(7)) / 2
M = np.array([[0, -1], [2, -1]])
t = np.array([np.conj(mu), 1.0])                        # row vector with t M = mu t
check("vacuum coordinate z = conj(mu) x1 + x2 turns the step into multiplication by mu = (-1 + sqrt(-7))/2", np.allclose(t @ M, mu * t))
scale = 1 / np.sqrt(np.sqrt(7) / 2)                     # unit cell of area 1
R = 6
grid = np.array([(a, b) for a in range(-R, R + 1) for b in range(-R, R + 1)])
def emb(pts):
    return (pts @ t) * scale
def sub(Mat):
    return np.array([Mat @ g for g in grid])
I2 = np.eye(2, dtype=int)
fig, axs = plt.subplots(1, 2, figsize=(10.4, 5.0), dpi=200)
panels = [("kernel tower", M, M @ M, "M L  (index 2)", "M² L  (index 4)"),
          ("point tower", I2 - M, I2 - M @ M, "(1 − M) L  (index 4)", "(1 − M²) L  (index 8)")]
for ax, (title, S1, S2, l1, l2) in zip(axs, panels):
    z0, z1, z2 = emb(grid), emb(sub(S1)), emb(sub(S2))
    ax.scatter(z0.real, z0.imag, s=7, color=AXIS, linewidths=0, zorder=2, label="L")
    ax.scatter(z1.real, z1.imag, s=30, color=BLUE, linewidths=0, zorder=3, label=l1)
    ax.scatter(z2.real, z2.imag, s=95, facecolors="none", edgecolors=ORANGE, linewidths=1.6, zorder=4, label=l2)
    ax.add_patch(plt.Circle((0, 0), 1 / np.sqrt(2 * np.pi) * np.sqrt(2), fill=False, color=MUTED, lw=0.8, ls=(0, (3, 3)), zorder=1))
    ax.set_xlim(-3.6, 3.6)
    ax.set_ylim(-3.6, 3.6)
    ax.set_aspect("equal")
    ax.set_title(title, fontsize=10.5, color=INK)
    ax.set_xticks([])
    ax.set_yticks([])
    for sp_ in ax.spines.values():
        sp_.set_visible(False)
    ax.legend(frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.01), ncol=3, fontsize=9, labelcolor=INK, handletextpad=0.3, columnspacing=1.2)
fig.tight_layout()
fig.savefig(os.path.join(NOTE, "fig_tower_lattice.png"))
plt.close(fig)

print(f"\n{npass} passed, {nfail} failed")
