/* ell_ref.c: reference data for the elliptic-curve instance, read from tests/data/ell_ref.txt.
 *
 * The file is generated by tools/pari_ref.py (PARI 2.17.2) and committed, so no C test ever needs
 * PARI. Format (one block per curve, terminated by `end`):
 *
 *     curve <label> <a1,a2,a3,a4,a6> <C> <w> <rank>
 *     ap <p> <a_p>                        (primes p <= 2500; read by Lane B's tests, not here)
 *     zero <k> <gamma_k>                  (40 decimal digits; a central zero is printed as `0`)
 *     end
 *
 * Conventions (notes/zeta-spectral-triples/ellcurve/astra-review.md, F1): the ANALYTIC
 * normalisation L_an(E, s) = L_ar(E, s + 1/2), zeros at s = 1/2 + i gamma, so the central zero of a
 * curve of analytic rank r appears as gamma_1 = ... = gamma_r = 0 and PARI lists it with its
 * multiplicity. These are PARI approximations, not certified zero enclosures: each is returned as a
 * ball of radius 1e-38, two digits inside the 40 printed, which is the accuracy the generator
 * requested (tools/pari_ref.py: lfunzeros at DIGITS + 10 and an explicit `precision` argument --
 * the review's "50-digit pins can use PARI display precision alone" correction).
 *
 * The minimal Weierstrass model and the conductor are INPUTS to zst_weil_ellcurve (header contract:
 * "both inputs; taken from tests/data/ell_ref.txt, never computed here"). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "zst.h"

#define ZST_ELL_REF_RAD "1e-38"

/* the file is looked for at `path` (when given), then at the two locations that make the tests work
 * from the zst directory and from build/ */
static FILE *
open_ref(const char *path)
{
    static const char *fallback[2] = { "tests/data/ell_ref.txt", "../tests/data/ell_ref.txt" };
    FILE *f;
    int i;
    if (path != NULL && (f = fopen(path, "r")) != NULL) return f;
    for (i = 0; i < 2; i++)
        if ((f = fopen(fallback[i], "r")) != NULL) return f;
    return NULL;
}

int zst_ell_ref(fmpz *ainvs, fmpz_t C, int *w, slong *rank, arb_ptr gamma, slong K,
                const char *label, const char *path, slong prec)
{
    FILE *f = open_ref(path);
    char line[512], lab[128], ai[256], val[256];
    slong k, nzeros = 0;
    long cond, rootno, rk;
    int found = 0;
    arb_t rad;

    if (f == NULL) return 0;
    arb_init(rad);
    arb_set_str(rad, ZST_ELL_REF_RAD, prec);

    for (k = 0; k < K; k++) arb_indeterminate(gamma + k);

    while (fgets(line, sizeof(line), f) != NULL)
    {
        if (!found)
        {
            if (line[0] != 'c') continue;
            if (sscanf(line, "curve %127s %255s %ld %ld %ld", lab, ai, &cond, &rootno, &rk) != 5) continue;
            if (strcmp(lab, label) != 0) continue;
            found = 1;
            {
                char *p = ai;
                for (k = 0; k < 5; k++)
                {
                    fmpz_set_si(ainvs + k, strtol(p, &p, 10));
                    if (*p == ',') p++;
                }
            }
            fmpz_set_si(C, cond);
            *w = (int) rootno;
            *rank = (slong) rk;
            continue;
        }
        if (line[0] == 'e' && !strncmp(line, "end", 3)) break;
        if (line[0] != 'z') continue;
        if (sscanf(line, "zero %ld %255s", &rk, val) != 2) continue;
        if (rk >= 1 && rk <= K)
        {
            arb_ptr g = gamma + (rk - 1);
            if (arb_set_str(g, val, prec) != 0) { arb_indeterminate(g); continue; }
            arb_add_error(g, rad);                         /* PARI approximation, not a certificate */
            nzeros++;
        }
    }
    fclose(f);
    arb_clear(rad);
    return found;
}
