#!/usr/bin/env python3
"""Run each example in isolation, aggregate tallies, regenerate the report's evidence appendix."""
from pathlib import Path
import json
import subprocess
import sys

HERE=Path(__file__).resolve().parent
NAMES=['e0_pair_shift','curve_affine','curve_projective','curve_supersingular',
       'z2_shift_cover','dirichlet_f2','dirichlet_f3','gauss','kloosterman',
       'graph_artin','independence','cmps_half','cmps_fe']

def main():
    total=0; failures=[]; results=[]
    for name in NAMES:
        p=subprocess.run([sys.executable,str(HERE/(name+'.py'))],capture_output=True,text=True)
        (HERE/'results'/(name+'.txt')).write_text(p.stdout+p.stderr)
        print(p.stdout, end='',flush=True)
        if p.returncode:
            print(p.stderr,flush=True); failures.append(name); continue
        result=json.loads((HERE/'results'/(name+'.json')).read_text())
        total+=result['checks']; results.append(result)
    print(f'TOTAL TALLY: {total} passed checks; {len(failures)} failed scripts; {len(results)}/{len(NAMES)} examples completed.',flush=True)
    if failures: raise SystemExit(1)
    appendix=['## Reproducible matrix and number catalogue\n',
              'Generated by `finite/run_all.py`. Every matrix entry below is an exact number '
              '(including radicals and the specified roots of unity); decimals are labelled. '
              'A repeated letter is a distinct orthonormal physical species. '
              'Matrix rows are printed in full, in row-major order.\n',
              f'**Verification: {total} passed checks; 0 failed scripts; {len(results)} example scripts.**\n']
    for result in results:
        name=result['name']
        appendix += [f'### `{name}.py` — {result["checks"]} checks\n',
                     f'Run: `python3 notes/zeta-conditions/finite/{name}.py`.\n']
        for label,value in result['formulas'].items(): appendix.append(f'- **{label}**: `{value}`')
        appendix.append('\n| Sequence | Entries in order |\n|---|---|')
        for label,values in result['sequences'].items(): appendix.append(f'| {label} | '+', '.join('`'+v+'`' for v in values)+' |')
        appendix.append('')
        for label,matrix in result['matrices'].items():
            appendix += [f'**{label}** ({len(matrix)} × {len(matrix[0])}):','```text']
            appendix += ['['+', '.join(row)+']' for row in matrix]
            appendix += ['```','']
        for fact in result['facts']: appendix.append(f'- {fact}')
        appendix.append('')
    generated='\n'.join(appendix)+'\n'
    (HERE/'results'/'evidence.md').write_text(generated)
    report=HERE.parent/'astra-constructions.md'
    marker='<!-- GENERATED EVIDENCE BELOW -->'
    if report.exists() and marker in report.read_text():
        head=report.read_text().split(marker)[0]
        report.write_text(head+marker+'\n\n'+generated)

if __name__=='__main__': main()
