#!/usr/bin/env python
"""Ground truth for the elliptic-curve extension of zst, from PARI through cypari2.

Writes tests/data/ell_ref.txt: for each test curve, the minimal model, conductor, root number,
analytic rank, a_p for every prime p <= PMAX, and the first K zero ordinates gamma (analytic
normalisation, s = 1/2 + i gamma) to DIGITS digits. The C tests read this file; they never need
PARI. Run with any python that has cypari2 (here: the scratch venv, see
notes/zeta-spectral-triples/ellcurve/plan.md Section 5). The PARI version is recorded in the header.
"""
import sys, datetime
import cypari2

CURVES = [("11a1", [0, -1, 1, -10, -20]), ("14a1", [1, 0, 1, 4, -6]),
          ("37a1", [0, 0, 1, -1, 0]), ("389a1", [0, 1, 1, -2, 0])]
PMAX, K, DIGITS, HMAX = 2500, 40, 40, 40.0
BITS = int(DIGITS * 3.33) + 24

def main(out):
    p = cypari2.Pari()
    p.default("realprecision", DIGITS + 10)
    with open(out, "w") as f:
        f.write(f"# ell_ref: generated by zst/tools/pari_ref.py, PARI {p.version()}, {datetime.date.today()}\n")
        f.write(f"# per curve: label ainvs N w rank; then 'ap p a_p' for primes <= {PMAX}; then 'zero k gamma' ({DIGITS} digits, gamma <= {HMAX})\n")
        for label, ai in CURVES:
            E = p.ellinit(ai); L = p.lfuncreate(E)
            N = int(p.ellglobalred(E)[0]); w = int(p.ellrootno(E)); r = int(p.lfunorderzero(L))
            assert list(p.ellminimalmodel(E)[:5]) == [p(x) for x in ai], label
            f.write(f"curve {label} {','.join(map(str, ai))} {N} {w} {r}\n")
            q = 2
            while q <= PMAX:
                f.write(f"ap {q} {int(p.ellap(E, q))}\n"); q = int(p.nextprime(q + 1))
            zeros = p.lfunzeros(L, HMAX, precision=BITS)
            for k, g in enumerate(zeros[:K], 1):
                f.write(f"zero {k} {str(g)[:DIGITS + 2] if float(g) != 0 else '0'}\n")
            f.write("end\n")
    print("wrote", out)

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "tests/data/ell_ref.txt")
