#!/usr/bin/env python3
"""A finite graph with a cusp: reflection coefficient, resonances, renewal channel.

Numerics lane for the brief `notes/cusp-graph/astra-brief.md` (conventions C1--C3,
statements T1, T3--T7).  Run blind to the prover's file.  Deterministic (seed
20260920); every check is an assertion, tally printed at the end.

--------------------------------------------------------------------------------
CONVENTIONS AND THE CONSTANTS FIXED HERE  (derived here, not taken from the brief)
--------------------------------------------------------------------------------
INDEXING.  Core vertices 0..n-1 with v_0 = 0; ray vertex r_k at ambient index
n+k-1, k = 1..L.  T = T_X (+) T_ray + c(|v_0><r_1| + |r_1><v_0|), with
(T g)(r_1) = g(r_2) + c g(v_0) and (T g)(r_k) = g(r_{k+1}) + g(r_{k-1}), k >= 2.

SPECTRAL PARAMETER.  lambda = z + 1/z;  |z| < 1  <->  Re s < 1/2 under z = q^{s-1/2}.

REFLECTION COEFFICIENT.  With g(r_k) = z^{-k} + R z^k for k >= 1 the junction
equation gives c g(v_0) = 1 + R and (lambda - T_X) g_X = c (z^{-1} + R z)|v_0>, hence
with G(lambda) = <v_0|(lambda - T_X)^{-1}|v_0>

    R(z) = (1 - c^2 G z^{-1}) / (c^2 G z - 1) .                       [G-form]

Since det(lambda - T_X - a P_0) = det(lambda - T_X)(1 - a G) and
z^n det(lambda - T_X - a P_0) = det((1+z^2) - z T_X - a z P_0),

    p(z)      := det((1+z^2) I - z T_X - c^2 P_0)        = z^n det(lam - T_X - c^2 z^-1 P_0)
    ptilde(z) := det((1+z^2) I - z T_X - c^2 z^2 P_0)    = z^n det(lam - T_X - c^2 z   P_0)
              =  z^{2n} p(1/z),

so that EXACTLY

    R(z) = - p(z)/ptilde(z)  =  - det(lam - T_X - c^2 z^{-1} P_0)/det(lam - T_X - c^2 z P_0).

The power of z the brief asks for is ZERO; what is missing in the brief's two
displayed determinant forms is the MINUS SIGN (its own G-form has it).  Sanity:
c -> 0 gives R -> -1, the Dirichlet reflection of the decoupled ray.

deg p = 2n with leading coefficient 1 and p(0) = det(I - c^2 P_0) = 1 - c^2, so
the product of ALL roots of p is exactly 1 - c^2 (no sign ambiguity).
deg ptilde = 2n with leading coefficient 1 - c^2: the degree DROPS at c = 1.

TRIVIAL / RESONANT SPLIT.  l^2 eigenfunctions decay as z^k on the ray and are the
roots of ptilde in |z| < 1 (equivalently self-consistent eigenvalues of
T_X + c^2 z P_0); resonances are the roots of p in |z| < 1 after cancellation
(self-consistent eigenvalues of T_X + (c^2/z) P_0).  Because
roots(ptilde) = 1/roots(p), writing p(z) = prod (z - z_i), ptilde(z) = prod (1 - z_i z),

    R(z) = - prod_i (z - z_i)/(1 - z_i z),

i.e. R is a Blaschke product over the roots of p INSIDE the disc divided by the
Blaschke product over the l^2 eigenvalues (the roots of ptilde inside).  R is
therefore NOT inner on the disc; the characteristic function of the Lax-Phillips
compression is R times the trivial Blaschke product.

BAND EDGE.  p(+-1) = ptilde(+-1) always, so z = +-1 (lambda = +-2) is a common root
whenever p(+-1) = 0, with no cusp form present.  This is the exception to C2(iii).

ENERGY FORM.  E = [[I, -T/2], [-T/2, I]] on l^2(Y) (+) l^2(Y), W = [[T, -I],[I, 0]],
E(u,v) = ||u||^2 + ||v||^2 - Re<u,Tv>;  W^* E W = E exactly.

TRANSLATION SUBSPACES.  D_+ = data whose FORWARD solution vanishes on the core for
all m >= 0; its generators are

    b_1 = (e_{r_1}, c e_{v_0}),   b_j = (e_{r_j}, e_{r_{j-1}})  (j >= 2),

the j = 1 generator being the one the naive "supported on the ray" reading misses.
D_- = data whose BACKWARD solution vanishes on the core for all m <= 0, generated by
f_j = (e_{r_j}, e_{r_{j+1}}), j >= 1.  K = H_LP (-)_E (D_+ (+) D_-) with
H_LP = the E-orthocomplement of all l^2 eigen-data; Z = P_K W|_K in the E-inner
product.  Vectors of K vanish on the ray beyond a bounded index, so a truncated ray
is EXACT for K (checked by varying the cut).

GRAM IDENTITY.  If C k_n = z_n k_n and 1 - C^*C = |j><j| then
<k_n,k_m>(1 - conj(z_n) z_m) = conj(<j|k_n>) <j|k_m>, i.e.

    <k_n, k_m> = conj(alpha_n) alpha_m / (1 - conj(z_n) z_m),   alpha_n = <j|k_n>,

which also forces alpha_n != 0.  This is the brief's guessed 1/(1 - z_n conj z_m)
with the normalisation made explicit.
--------------------------------------------------------------------------------
"""
import numpy as np
import scipy.linalg as sla

np.set_printoptions(linewidth=170, precision=6, suppress=True)
rng = np.random.default_rng(20260920)

CHECKS = 0
FLAGS = []


def check(cond, msg):
    global CHECKS
    CHECKS += 1
    assert cond, f"FAILED  {msg}"
    print(f"  ok {CHECKS:3d}  {msg}")


def flag(msg):
    FLAGS.append(msg)
    print(f"  !! {msg}")


def f6(x):
    return f"{float(x) + 0.0:+.6f}"


def c6(z):
    z = complex(z)
    return f"{z.real + 0.0:+.6f}{z.imag + 0.0:+.6f}j"


def clist(zs):
    return "[" + ", ".join(c6(z) for z in sortc(zs)) + "]"


def flist(xs):
    return "[" + ", ".join(f6(x) for x in sorted(float(x) for x in xs)) + "]"


def flist_raw(xs):
    return "[" + ", ".join(f6(x) for x in xs) + "]"


def sortc(zs):
    return sorted(zs, key=lambda t: (round(complex(t).real, 8), round(complex(t).imag, 8)))


# ---------------------------------------------------------------- the diagram Y
def build_T(TX, c, L):
    """T on core (indices 0..n-1, v_0 = 0) plus ray r_1..r_L (indices n..n+L-1)."""
    n = TX.shape[0]
    N = n + L
    T = np.zeros((N, N))
    T[:n, :n] = TX
    T[0, n] = c
    T[n, 0] = c
    for k in range(1, L):
        T[n + k - 1, n + k] = 1.0
        T[n + k, n + k - 1] = 1.0
    return T


def P0_of(n):
    P = np.zeros((n, n))
    P[0, 0] = 1.0
    return P


def poly_coeffs(matfun, deg):
    """Coefficients (low to high) of det matfun(z), a polynomial of degree <= deg,
    by evaluation at (deg+1)-th roots of unity and an inverse DFT."""
    N = deg + 1
    w = np.exp(2j * np.pi * np.arange(N) / N)
    vals = np.array([np.linalg.det(matfun(x)) for x in w])
    # vals[j] = sum_k a_k w^{jk}, so a = fft(vals)/N  (ifft would reverse the index)
    return np.fft.fft(vals) / N


def p_poly(TX, c):
    n = TX.shape[0]
    P0 = P0_of(n)
    I = np.eye(n)
    return poly_coeffs(lambda z: (1 + z * z) * I - z * TX - c * c * P0, 2 * n)


def pt_poly(TX, c):
    n = TX.shape[0]
    P0 = P0_of(n)
    I = np.eye(n)
    return poly_coeffs(lambda z: (1 + z * z) * I - z * TX - c * c * z * z * P0, 2 * n)


def polyroots(co, tol=1e-11):
    """Roots of sum_k co[k] z^k (co low-to-high), trimming negligible leading terms."""
    a = np.array(co, dtype=complex)
    scale = max(np.max(np.abs(a)), 1.0)
    k = len(a) - 1
    while k > 0 and abs(a[k]) < tol * scale:
        k -= 1
    if k == 0:
        return np.array([], dtype=complex)
    return np.roots(a[:k + 1][::-1])


def evalpoly(co, z):
    return sum(co[k] * z ** k for k in range(len(co)))


def common_split(rp, rpt, tol=1e-6):
    """Greedy multiset match of roots(p) against roots(ptilde)."""
    pool = list(rpt)
    common, rest = [], []
    for z in rp:
        best, bd = None, tol
        for i, w in enumerate(pool):
            d = abs(z - w)
            if d < bd:
                bd, best = d, i
        if best is None:
            rest.append(z)
        else:
            common.append(z)
            pool.pop(best)
    return common, rest


def cusp_forms(TX, tol=1e-9):
    """(lambda, psi) with T_X psi = lambda psi and psi(v_0) = 0."""
    n = TX.shape[0]
    w, V = np.linalg.eigh(TX)
    out = []
    i = 0
    while i < n:
        j = i
        while j + 1 < n and abs(w[j + 1] - w[i]) < 1e-9:
            j += 1
        blk = V[:, i:j + 1]
        row = blk[0, :].reshape(1, -1)
        if np.linalg.norm(row) < tol:
            for k in range(blk.shape[1]):
                out.append((w[i], blk[:, k]))
        else:
            Q = sla.null_space(row, rcond=1e-10)
            for k in range(Q.shape[1]):
                out.append((w[i], blk @ Q[:, k]))
        i = j + 1
    return out


def krylov(TX, tol=1e-9):
    """Orthonormal basis Q (first column e_{v_0}) of the Krylov space of T_X at v_0.
    Its orthocomplement is the largest T_X-invariant subspace inside v_0^perp, i.e.
    exactly the cusp forms, so p factorises as p_red * (cusp factors)."""
    n = TX.shape[0]
    Q = []
    w = np.zeros(n)
    w[0] = 1.0
    for _ in range(n):
        for _ in range(2):
            for q in Q:
                w = w - (q @ w) * q
        nw = np.linalg.norm(w)
        if nw < tol:
            break
        q = w / nw
        Q.append(q)
        w = TX @ q
    return np.array(Q).T


CIRC = 1e-6


def spectrum_data(TX, c):
    """Everything the polynomial picture gives: roots, resonances, trivial modes.
    Root finding is done on the Krylov block only, where no root is forced to be
    multiple by a cusp form; the cusp factors are deflated analytically."""
    n = TX.shape[0]
    Q = krylov(TX)
    TXk = Q.T @ TX @ Q
    dK = TXk.shape[0]
    pc_f, ptc_f = p_poly(TX, c), pt_poly(TX, c)
    pc, ptc = p_poly(TXk, c), pt_poly(TXk, c)
    rp = polyroots(pc)
    rpt = polyroots(ptc)
    edge = [z for z in rp if min(abs(z - 1), abs(z + 1)) < CIRC]
    circ = [z for z in rp if abs(abs(z) - 1) < CIRC and min(abs(z - 1), abs(z + 1)) >= CIRC]
    res = [z for z in rp if abs(z) < 1 - CIRC]
    out = [z for z in rp if abs(z) > 1 + CIRC]
    triv_nc = [1 / z for z in out]
    cf = cusp_forms(TX)
    cusp_roots = []
    triv_cusp = []
    for lam, _ in cf:
        zz = np.roots([1.0, -lam, 1.0])
        cusp_roots += list(zz)
        for z in zz:
            if abs(z) < 1 - CIRC:
                triv_cusp.append(z)
    triv_z = list(triv_nc) + triv_cusp
    triv_lam = sorted((z + 1 / z).real for z in triv_z)
    return dict(n=n, dK=dK, c=c, pc=pc_f.real, ptc=ptc_f.real, pc_red=pc.real,
                rp=list(rp) + cusp_roots, rp_red=list(rp), rpt=list(rpt),
                res=res, out=out, circ=circ, triv_z=triv_z, triv_nc=triv_nc,
                triv_lam=triv_lam, cusp=cf, cusp_roots=cusp_roots, n_edge=len(edge))


def R_closed(TX, c, z):
    """R from the exact rational form -p/ptilde."""
    return -evalpoly(p_poly(TX, c), z) / evalpoly(pt_poly(TX, c), z)


def R_direct(TX, c, z, L):
    """R by solving T g = lambda g on core + ray with g(r_k) = z^-k + R z^k imposed
    at the two outermost sites.  The ansatz solves the free ray recursion exactly,
    so this is an EXACT linear system, not a truncation: any L >= 3 gives the same R."""
    n = TX.shape[0]
    lam = z + 1 / z
    M = n + L + 1                      # unknowns: g_X (n), g(r_1..r_L), R
    A = np.zeros((M, M), dtype=complex)
    b = np.zeros(M, dtype=complex)
    r = 0
    for i in range(n):                 # core equations
        A[r, :n] = TX[i, :] - lam * np.eye(n)[i, :]
        if i == 0:
            A[r, n] += c
        r += 1
    A[r, n + 1] = 1.0                  # k = 1: g(r_2) + c g(v_0) - lam g(r_1) = 0
    A[r, 0] += c
    A[r, n] -= lam
    r += 1
    for k in range(2, L):              # k = 2..L-1
        A[r, n + k] = 1.0
        A[r, n + k - 2] = 1.0
        A[r, n + k - 1] = -lam
        r += 1
    for k in (L - 1, L):               # boundary fit
        A[r, n + k - 1] = 1.0
        A[r, M - 1] = -z ** k
        b[r] = z ** (-k)
        r += 1
    assert r == M
    x = np.linalg.solve(A, b)
    return x[M - 1], x


# ---------------------------------------------------------------- l^2 eigenvectors
def l2_eigvecs(TX, c, L):
    """Exact l^2 eigenvectors of T on the (truncated) Y: cusp forms extended by
    zero, and the trivial modes g_X = w, g(r_k) = c<v_0|w> z^k."""
    n = TX.shape[0]
    P0 = P0_of(n)
    out = []
    for lam, psi in cusp_forms(TX):
        g = np.concatenate([psi, np.zeros(L)])
        out.append((lam, g / np.linalg.norm(g)))
    for z in spectrum_data(TX, c)["triv_nc"]:
        if abs(z.imag) > 1e-8:
            continue
        zr = z.real
        lam = zr + 1 / zr
        ns = sla.null_space(lam * np.eye(n) - TX - c * c * zr * P0, rcond=1e-8)
        for k in range(ns.shape[1]):
            w = ns[:, k].real
            alpha = c * w[0]
            if abs(alpha) < 1e-9:
                continue               # a cusp form, already listed
            g = np.concatenate([w, alpha * zr ** np.arange(1, L + 1)])
            out.append((lam, g / np.linalg.norm(g)))
    return out


# ---------------------------------------------------------------- Lax-Phillips K, Z
def lp_pieces(TX, c, L):
    """T, the energy matrix E, the wave step W, and the D_+ / D_- generators."""
    n = TX.shape[0]
    N = n + L
    T = build_T(TX, c, L)
    I = np.eye(N)
    E = np.block([[I, -T / 2], [-T / 2, I]])
    Wm = np.block([[T, -I], [I, np.zeros((N, N))]])

    def bvec(j):                                  # outgoing generator
        g = np.zeros(2 * N)
        g[n + j - 1] = 1.0
        if j == 1:
            g[N + 0] = c
        else:
            g[N + n + j - 2] = 1.0
        return g

    def fvec(j):                                  # incoming generator
        g = np.zeros(2 * N)
        g[n + j - 1] = 1.0
        g[N + n + j] = 1.0
        return g

    return n, N, T, E, Wm, bvec, fvec


def K_compact(TX, c, M=8, L=200, jstart=2, with_eig=True, rtol=1e-8):
    """The compactly supported part of K: vectors on core + r_1..r_M that are
    E-orthogonal to D_+ = span{b_j, j >= jstart}, to D_- = span{f_j, j >= 1} and
    (optionally) to all l^2 eigen-data.  Generators beyond j = M+3 give zero rows."""
    n, N, T, E, Wm, bvec, fvec = lp_pieces(TX, c, L)
    m = n + M
    S = np.zeros((2 * N, 2 * m))
    S[:m, :m] = np.eye(m)
    S[N:N + m, m:] = np.eye(m)
    ES = E @ S
    rows = [bvec(j) @ ES for j in range(jstart, M + 5)]
    rows += [fvec(j) @ ES for j in range(1, M + 5)]
    if with_eig:
        for lam, psi in l2_eigvecs(TX, c, L):
            d = np.zeros(2 * N)
            d[:N] = psi
            rows.append(d @ ES)
            d = np.zeros(2 * N)
            d[N:] = psi
            rows.append(d @ ES)
    A = np.array(rows)
    s = np.linalg.svd(A, compute_uv=False)
    rank = int(np.sum(s > rtol * s[0]))
    return 2 * m - rank


def gram_model(zs):
    """The Sz.-Nagy--Foias functional model of a contraction with defect indices
    (1,1) and characteristic function the Blaschke product over the DISTINCT
    resonances zs: Gram G_nm = 1/(1 - conj(z_n) z_m), C k_n = z_n k_n, <j|k_n> = 1."""
    zs = np.array(zs, dtype=complex)
    d = len(zs)
    G = 1.0 / (1 - np.outer(zs.conj(), zs))
    ev, U = np.linalg.eigh(G)
    assert ev.min() > 1e-12, f"Gram matrix not positive definite: {ev}"
    Rh = U @ np.diag(np.sqrt(ev)) @ U.conj().T
    Ri = U @ np.diag(1 / np.sqrt(ev)) @ U.conj().T
    C = Rh @ np.diag(zs) @ Ri
    jj = Ri @ np.ones(d)
    return dict(d=d, z=zs, G=G, C=C, j=jj, V=Rh, cond=ev.max() / ev.min())


def char_fn(C, jj, w):
    """The scalar characteristic function of a contraction with defect one."""
    d = C.shape[0]
    dc = np.eye(d) - C.conj().T @ C
    dcs = np.eye(d) - C @ C.conj().T
    ev, U = np.linalg.eigh(dc)
    jh = U[:, -1]
    ev2, U2 = np.linalg.eigh(dcs)
    jh2 = U2[:, -1]
    a = -(jh2.conj() @ (C @ jh))
    b = w * np.sqrt(ev[-1] * ev2[-1]) * (
        jh2.conj() @ np.linalg.solve(np.eye(d) - w * C.conj().T, jh))
    return a + b


def blaschke(zs, w):
    out = 1.0 + 0.0j
    for z in zs:
        out *= (z - w) / (1 - np.conj(z) * w)
    return out


# ---------------------------------------------------------------- renewal channel
def superop(C, Om, jj):
    """E_Omega(rho) = C rho C^* + <j|rho|j> Omega, row-major vec."""
    J = np.outer(jj, jj.conj())
    return np.kron(C, C.conj()) + np.outer(Om.reshape(-1), J.T.reshape(-1))


def apply_E(C, Om, jj, rho):
    return C @ rho @ C.conj().T + (jj.conj() @ rho @ jj).real * Om


def stein(C, Om):
    """X = sum_{m>=0} C^m Omega C^*m, the exact renewal sum (Stein equation
    X - C X C^* = Omega); used instead of a truncated sum because resonances can
    sit very close to the unit circle."""
    X = sla.solve_discrete_lyapunov(C, Om)
    return 0.5 * (X + X.conj().T)


def mhat(C, Om, jj, u):
    """mhat(u) = sum_m m(m) u^m = u <j|(1 - u E_0)^-1 Omega|j>, computed exactly."""
    d = C.shape[0]
    E0 = np.kron(C, C.conj())
    X = np.linalg.solve(np.eye(d * d) - u * E0, Om.reshape(-1)).reshape(d, d)
    return u * (jj.conj() @ X @ jj)


def rand_density(d, gen):
    A = gen.normal(size=(d, d)) + 1j * gen.normal(size=(d, d))
    rho = A @ A.conj().T
    return rho / np.trace(rho).real


# ================================================================ header
print(__doc__.split("-------")[0].strip())
print()
print("seed 20260920; core index 0 is always v_0")

# ================================================================ C1
print("\n" + "=" * 78)
print("C1  normalisation of the tree quotient, and the reflection coefficient")
print("=" * 78)

for q in (2, 3, 5):
    # A f(Lam_n) = f(Lam_{n+1}) + q f(Lam_{n-1}) (n>=1),  A f(Lam_0) = (q+1) f(Lam_1)
    NL = 12
    A = np.zeros((NL, NL))
    A[0, 1] = q + 1
    for nn in range(1, NL - 1):
        A[nn, nn + 1] = 1.0
        A[nn, nn - 1] = q
    A[NL - 1, NL - 2] = q
    # measure forced by self-adjointness of A on L^2(Y,m):
    #   m_0 (q+1) = m_1 q      and     m_n * 1 = m_{n+1} * q  (n >= 1)
    mm = np.ones(NL)
    mm[1] = (q + 1) / q
    for nn in range(1, NL - 1):
        mm[nn + 1] = mm[nn] / q
    Aw = np.diag(mm) @ A
    check(np.max(np.abs(Aw - Aw.T)) < 1e-12,
          f"q={q}: A is self-adjoint on L^2(Y,m) iff m_0=1, m_1=(q+1)/q, m_n=(q+1)q^-n (n>=1); "
          f"the brief's m ~ q^-n holds only for n>=1 (junction correction (q+1)/q at n=0..1)")
    mnaive = q ** (-np.arange(NL, dtype=float))
    An = np.diag(mnaive) @ A
    check(np.max(np.abs(An - An.T)) > 0.5,
          f"q={q}: with the uncorrected m_n = q^-n for ALL n, A is NOT symmetric "
          f"(max asymmetry {np.max(np.abs(An - An.T)):.4f})")
    Atil = np.diag(np.sqrt(mm)) @ A @ np.diag(1 / np.sqrt(mm)) / np.sqrt(q)
    Tref = build_T(np.zeros((1, 1)), np.sqrt(q + 1.0), NL - 1)
    check(np.max(np.abs(Atil - Tref)) < 1e-12,
          f"q={q}: g = m^1/2 f and division by sqrt q turn A into T_X=[0] (+) path adjacency "
          f"with junction c = sqrt(q+1), i.e. c^2 = q+1 = {q+1} exactly")

TX1 = np.array([[0.7]])
for (TX, c, tag) in [(np.array([[0.0]]), np.sqrt(3.0), "pure cusp q=2"),
                     (TX1, 1.3, "1-vertex loop a=0.7 c=1.3"),
                     (np.array([[0.2, 0.5, 0.0], [0.5, -0.3, 0.9], [0.0, 0.9, 0.4]]), 0.8,
                      "3-vertex core")]:
    n = TX.shape[0]
    G_dev = Rp_dev = det_dev = sgn_dev = 0.0
    for th in (0.3, 0.9, 1.7, 2.6):
        z = np.exp(1j * th)
        lam = z + 1 / z
        Rd, _ = R_direct(TX, c, z, 40)
        Rd2, _ = R_direct(TX, c, z, 200)
        G = np.linalg.inv(lam * np.eye(n) - TX)[0, 0]
        Rg = (1 - c * c * G / z) / (c * c * G * z - 1)
        P0 = P0_of(n)
        Rdet = (np.linalg.det(lam * np.eye(n) - TX - c * c * P0 / z)
                / np.linalg.det(lam * np.eye(n) - TX - c * c * z * P0))
        Rp = -evalpoly(p_poly(TX, c), z) / evalpoly(pt_poly(TX, c), z)
        G_dev = max(G_dev, abs(Rd - Rg), abs(Rd - Rd2))
        Rp_dev = max(Rp_dev, abs(Rd - Rp))
        det_dev = max(det_dev, abs(Rd - Rdet))
        sgn_dev = max(sgn_dev, abs(Rd + Rdet))
    check(G_dev < 1e-9,
          f"{tag}: R from the direct ray solve (L=40 and L=200 identical) = the G-form "
          f"(1 - c^2 G/z)/(c^2 G z - 1), max dev {G_dev:.2e}")
    check(Rp_dev < 1e-9,
          f"{tag}: R = -p(z)/ptilde(z) EXACTLY -- the power of z is 0 and the brief's "
          f"'R = p/ptilde' is off by the sign -1 (max dev {Rp_dev:.2e})")
    check(sgn_dev < 1e-9 and det_dev > 1e-3,
          f"{tag}: the brief's determinant ratio equals -R, not R (dev from -R {sgn_dev:.2e}, "
          f"from +R {det_dev:.2e})")

for (TX, c, tag) in [(np.array([[0.0]]), np.sqrt(3.0), "pure cusp q=2"),
                     (TX1, 1.3, "1-vertex loop a=0.7 c=1.3"),
                     (np.array([[0.2, 0.5, 0.0], [0.5, -0.3, 0.9], [0.0, 0.9, 0.4]]), 0.8,
                      "3-vertex core")]:
    n = TX.shape[0]
    pc, ptc = p_poly(TX, c), pt_poly(TX, c)
    check(np.max(np.abs(pc.imag)) < 1e-12 and np.max(np.abs(ptc.imag)) < 1e-12,
          f"{tag}: p and ptilde have real coefficients (max |Im| "
          f"{max(np.max(np.abs(pc.imag)), np.max(np.abs(ptc.imag))):.1e})")
    rev = pc[::-1]
    check(np.max(np.abs(ptc - rev)) < 1e-11,
          f"{tag}: ptilde(z) = z^2n p(1/z) verified on coefficients (dev "
          f"{np.max(np.abs(ptc - rev)):.1e})")
    check(abs(pc[2 * n] - 1) < 1e-11 and abs(pc[0] - (1 - c * c)) < 1e-11,
          f"{tag}: deg p = 2n = {2*n}, leading coeff 1, p(0) = 1 - c^2 = {f6(1-c*c)}; "
          f"so prod of ALL roots of p = 1 - c^2 exactly (not just 'up to sign')")
    check(abs(ptc[2 * n] - (1 - c * c)) < 1e-11,
          f"{tag}: leading coeff of ptilde = 1 - c^2 = {f6(1-c*c)} (degree drops at c = 1)")
    mods = []
    for th in (0.2, 1.1, 2.0, 2.9):
        z = np.exp(1j * th)
        Rd, _ = R_direct(TX, c, z, 60)
        Rinv, _ = R_direct(TX, c, 1 / z, 60)
        mods.append(abs(abs(Rd) - 1))
        check(abs(Rd * Rinv - 1) < 1e-9 and abs(abs(Rd) - 1) < 1e-9,
              f"{tag}: at z = e^(i {th:.1f}), |R| = 1 (dev {abs(abs(Rd)-1):.1e}) and "
              f"R(z)R(1/z) = 1 (dev {abs(Rd*Rinv-1):.1e})")
    for x in (0.4, 1.7):
        z = 0.5 + 1j * x
        Ra = R_closed(TX, c, z)
        Rb = R_closed(TX, c, np.conj(z))
        check(abs(Rb - np.conj(Ra)) < 1e-11,
              f"{tag}: R(conj z) = conj R(z) at z = {c6(z)} (dev {abs(Rb-np.conj(Ra)):.1e})")
    d_num = len(polyroots(pc))
    d_den = len(polyroots(ptc))
    check(d_num == 2 * n and d_den == 2 * n,
          f"{tag}: deg R = 2n/2n = {d_num}/{d_den} as a rational map (before cancellation)")

# ================================================================ C2
print("\n" + "=" * 78)
print("C2  classification of the zeros and poles of R in the unit disc")
print("=" * 78)


def regular_TX(A, q):
    return A / np.sqrt(q)


K4 = np.ones((4, 4)) - np.eye(4)
CUBE = np.zeros((8, 8))
for i in range(8):
    for b in range(3):
        CUBE[i, i ^ (1 << b)] = 1.0
PET = np.zeros((10, 10))
_pe = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 0), (0, 5), (1, 6), (2, 7), (3, 8), (4, 9),
       (5, 7), (7, 9), (9, 6), (6, 8), (8, 5)]
for a, b in _pe:
    PET[a, b] = PET[b, a] = 1.0

# a core with a deliberate cusp form: v_0 = 0 joined to 1 and 2 with equal weight,
# the swap 1 <-> 2 is a symmetry, so (e_1 - e_2)/sqrt 2 vanishes at v_0.
def cuspy(w, s=0.0, t=0.9):
    return np.array([[0.0, t, t], [t, s, w], [t, w, s]])


CORES = [("pure cusp q=2", np.zeros((1, 1)), np.sqrt(3.0)),
         ("pure cusp q=5", np.zeros((1, 1)), np.sqrt(6.0)),
         ("free half line (c=1)", np.zeros((1, 1)), 1.0),
         ("loop a=1.0 c^2=0.5", np.array([[1.0]]), np.sqrt(0.5)),
         ("loop a=0.0 c^2=1.5", np.array([[0.0]]), np.sqrt(1.5)),
         ("loop a=0.5 c^2=1.2", np.array([[0.5]]), np.sqrt(1.2)),
         ("loop a=1.0 c^2=3 (band edge)", np.array([[1.0]]), np.sqrt(3.0)),
         ("loop a=1.0 c^2=4", np.array([[1.0]]), 2.0),
         ("cuspy w=-3 (cusp lam=3 outside band)", cuspy(-3.0), 1.1),
         ("cuspy w=1 (cusp lam=-1 embedded)", cuspy(1.0), 1.1),
         ("K4, q=2, c^2=3", regular_TX(K4, 2), np.sqrt(3.0)),
         ("3-cube, q=2, c^2=3", regular_TX(CUBE, 2), np.sqrt(3.0)),
         ("Petersen, q=2, c^2=3", regular_TX(PET, 2), np.sqrt(3.0))]
for k in (3, 4, 5):
    for r in range(2):
        A = rng.normal(size=(k, k))
        A = np.round(0.5 * (A + A.T), 3)
        CORES.append((f"random {k}-vertex core #{r+1}", A, float(np.round(0.6 + 0.5 * r, 3))))

print("\n-- per core: resonances, trivial l^2 modes, cusp forms, the count formula")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    n = sd["n"]
    cf = sd["cusp"]
    mu = len(cf)
    e = sum(1 for lam, _ in cf if abs(lam) < 2 - 1e-9)
    beta = sd["n_edge"]
    t = len(sd["triv_z"])
    tnc = len(sd["triv_nc"])
    pred = 2 * (n - mu) - tnc - beta
    check(len(sd["res"]) == pred == 2 * n - t - mu - e - beta and sd["dK"] == n - mu,
          f"{tag}: #res = {len(sd['res'])} = 2(n - mu) - t_nc - beta = 2*({n} - {mu}) - "
          f"{tnc} - {beta} = 2n - t - mu - e - beta (t={t}, e={e}); and "
          f"dim Krylov(T_X, v_0) = {sd['dK']} = n - mu")
    check(len(sd["circ"]) == 0,
          f"{tag}: the Krylov block p_red has no root on |z| = 1 except the band edge "
          f"({len(sd['circ'])} strays); so all unit-circle roots of p are cusp forms or +-1")

print("\n-- poles inside the disc are real and are l^2 eigenvalues (long-ray check)")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    tz = sd["triv_z"]
    check(all(abs(z.imag) < 1e-9 for z in tz),
          f"{tag}: every root of ptilde in |z|<1 is real "
          f"(max |Im| {max([abs(z.imag) for z in tz], default=0.0):.1e}); "
          f"z = {flist([z.real for z in tz])}")
    L = 400
    T = build_T(TX, c, L)
    w, V = np.linalg.eigh(T)
    out = [(w[i], V[:, i]) for i in range(len(w)) if abs(w[i]) > 2 + 1e-6]
    lam_num = sorted(x for x, _ in out)
    tails = [np.linalg.norm(v[-40:]) for _, v in out]
    check(len(lam_num) == len(sd["triv_lam"])
          and (len(lam_num) == 0
               or max(abs(a - b) for a, b in zip(lam_num, sd["triv_lam"])) < 1e-7),
          f"{tag}: truncated ray L=400 gives l^2 eigenvalues outside [-2,2] "
          f"{flist(lam_num)} = {{z + 1/z}} from ptilde (max dev "
          f"{max([abs(a-b) for a, b in zip(lam_num, sd['triv_lam'])], default=0.0):.1e})")
    check(max(tails, default=0.0) < 1e-6,
          f"{tag}: those eigenvectors decay (max tail norm on the last 40 ray sites "
          f"{max(tails, default=0.0):.1e}) -- they are genuinely l^2")

print("\n-- resonances: roots of p not shared with ptilde; conjugate pairs; effective operator")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    n, res = sd["n"], sd["res"]
    ok = True
    for z in res:
        lam = z + 1 / z
        M = lam * np.eye(n) - TX - (c * c / z) * P0_of(n)
        ok = ok and abs(np.linalg.det(M)) < 1e-7 * max(1.0, abs(lam) ** n)
    check(ok, f"{tag}: every resonance solves det(lam - T_X - (c^2/z) P_0) = 0 with "
              f"lam = z + 1/z (outgoing self-energy); res = {clist(res)}")
    nonreal = [z for z in res if abs(z.imag) > 1e-8]
    paired = all(any(abs(np.conj(z) - w) < 1e-7 for w in nonreal) for z in nonreal)
    check(paired, f"{tag}: the {len(nonreal)} non-real resonances come in conjugate pairs")
    ok2 = True
    for z in sd["triv_z"]:
        lam = z + 1 / z
        M = lam * np.eye(n) - TX - (c * c * z) * P0_of(n)
        ok2 = ok2 and abs(np.linalg.det(M)) < 1e-7 * max(1.0, abs(lam) ** n)
    check(ok2, f"{tag}: every trivial mode solves det(lam - T_X - c^2 z P_0) = 0 "
               f"(incoming branch)")

print("\n-- common factors of p and ptilde: cusp forms, PLUS the band edge z = +-1")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    n = sd["n"]
    cf = sd["cusp"]
    prod = np.array([1.0])
    for lam, _ in cf:
        prod = np.convolve(prod, np.array([1.0, -lam, 1.0]))
    full = np.convolve(sd["pc_red"], prod)
    check(len(full) == len(sd["pc"]) and np.max(np.abs(full - sd["pc"])) < 1e-8,
          f"{tag}: p(z) = p_red(z) * prod_cusp (z^2 - lam z + 1) exactly, with p_red the "
          f"Krylov block of dimension {sd['dK']} (coefficient dev "
          f"{np.max(np.abs(full - sd['pc'])):.1e})")
    com, _ = common_split(sd["rp_red"], sd["rpt"], tol=1e-6)
    edge_exp = [z for z in sd["rp_red"] if min(abs(z - 1), abs(z + 1)) < CIRC]
    check(len(com) == len(edge_exp) == sd["n_edge"],
          f"{tag}: p_red and ptilde_red share ONLY the band-edge roots z = +-1 "
          f"({sd['n_edge']} of them); every other common factor of p, ptilde is a cusp form")

sd_edge = spectrum_data(np.array([[1.0]]), np.sqrt(3.0))
check(sd_edge["n_edge"] == 1 and len(sd_edge["cusp"]) == 0,
      "loop a=1 c^2=3: p and ptilde share the root z = -1 (lambda = -2) although the core has "
      "NO cusp form -- C2(iii) is false as stated; p(+-1) = ptilde(+-1) identically")

sd_c = spectrum_data(cuspy(-3.0), 1.1)
lam_cusp = [lam for lam, _ in sd_c["cusp"]]
poles_R = sd_c["triv_nc"]
check(len(sd_c["cusp"]) == 1 and abs(lam_cusp[0] - 3.0) < 1e-9
      and len(sd_c["triv_z"]) == len(poles_R) + 1,
      f"cuspy w=-3: the cusp form has lambda = {f6(lam_cusp[0])} OUTSIDE [-2,2], so it IS an "
      f"l^2 eigenvalue ({len(sd_c['triv_z'])} of them) but is NOT a pole of R "
      f"({len(poles_R)} poles) -- C2(i) is too strong")

sd_c2 = spectrum_data(cuspy(1.0), 1.1)
lam_c2 = [lam for lam, _ in sd_c2["cusp"]]
check(len(sd_c2["cusp"]) == 1 and abs(lam_c2[0]) < 2,
      f"cuspy w=1: the cusp form has lambda = {f6(lam_c2[0])} embedded in [-2,2]; its two "
      f"z-roots sit on |z| = 1 and are invisible to R")

TXc = cuspy(-3.0)
psi = cusp_forms(TXc)[0][1]
Lc = 200
gg = np.concatenate([psi, np.zeros(Lc)])
Tc = build_T(TXc, 1.1, Lc)
check(np.max(np.abs(Tc @ gg - cusp_forms(TXc)[0][0] * gg)) < 1e-12,
      "cuspy w=-3: the cusp form extended by zero is an exact l^2 eigenvector of T on Y")

print("\n-- Blaschke structure of R (why R is not the characteristic function)")
for tag, TX, c in CORES[:8]:
    sd = spectrum_data(TX, c)
    rp = sd["rp"]
    dev = 0.0
    for th in (0.4, 1.3, 2.2):
        z = np.exp(1j * th)
        prod = -np.prod([(z - zi) / (1 - zi * z) for zi in rp])
        dev = max(dev, abs(prod - R_closed(TX, c, z)))
    check(dev < 1e-8,
          f"{tag}: R(z) = -prod_i (z - z_i)/(1 - z_i z) over the roots of p "
          f"(dev {dev:.1e}); the factors with |z_i|<1 are Blaschke, those with |z_i|>1 "
          f"are INVERSE Blaschke, so R is not inner on the disc")

# ================================================================ C3
print("\n" + "=" * 78)
print("C3  the pure cusp")
print("=" * 78)
for q in (2, 3, 5, 7):
    c = np.sqrt(q + 1.0)
    TX = np.zeros((1, 1))
    sd = spectrum_data(TX, c)
    pc, ptc = sd["pc"], sd["ptc"]
    check(np.max(np.abs(pc - np.array([-q, 0.0, 1.0]))) < 1e-10
          and np.max(np.abs(ptc - np.array([1.0, 0.0, -q]))) < 1e-10,
          f"q={q}: p(z) = z^2 - q and ptilde(z) = 1 - q z^2, so "
          f"R(z) = -p/ptilde = (z^2 - q)/(q z^2 - 1) -- the brief's C3 R is CORRECT")
    dev = max(abs(R_direct(TX, c, np.exp(1j * th), 60)[0]
                  - (np.exp(2j * th) - q) / (q * np.exp(2j * th) - 1))
              for th in (0.3, 1.2, 2.5))
    check(dev < 1e-10, f"q={q}: the direct ray solve confirms it (dev {dev:.1e})")
    check(len(sd["res"]) == 0 and len(sd["triv_z"]) == 2
          and abs(sorted(z.real for z in sd["triv_z"])[1] - q ** -0.5) < 1e-10,
          f"q={q}: no resonances; poles at z = +-q^-1/2 = {f6(q**-0.5)}, "
          f"zeros at +-q^1/2 outside")

    def zeta_K(s):
        return 1.0 / ((1 - q ** (-s)) * (1 - q ** (1.0 - s)))

    dR = dRi = 0.0
    for s in (0.31 + 0.22j, 0.77 - 0.4j, 1.3 + 0.9j):
        z = q ** (s - 0.5)
        phi = q * zeta_K(2 * s - 1) / zeta_K(2 * s)
        Rv = (z ** 2 - q) / (q * z ** 2 - 1)
        dR = max(dR, abs(phi - Rv))
        dRi = max(dRi, abs(phi - 1 / Rv))
    check(dRi < 1e-9 < dR,
          f"q={q}: q zeta_K(2s-1)/zeta_K(2s) = 1/R(z), NOT R(z) (dev from 1/R {dRi:.1e}, "
          f"from R {dR:.1e}); so phi = 1/R, with the pole at s=1 (z=q^1/2) and the zero at "
          f"s=0 (z=q^-1/2)")
flag("phi = 1/R: the poles of phi in |z| < 1 are the ZEROS of R, i.e. the resonances, "
     "which is what makes 'poles of phi with Re s < 1/2 = eigenvalues of the compression' "
     "consistent with C2(iv)")

# ================================================================ T1
print("\n" + "=" * 78)
print("T1  the discrete wave group, D_+, D_-, K and the compressed contraction Z")
print("=" * 78)

TXw = np.array([[0.3, 0.7], [0.7, -0.2]])
cw = 1.1
Lw = 60
nw, Nw, Tw, Ew, Ww, bvec_w, fvec_w = lp_pieces(TXw, cw, Lw)
check(np.max(np.abs(Ww.T @ Ew @ Ww - Ew)) < 1e-11,
      f"T1(a) W^T E W = E exactly: the energy form is W-invariant "
      f"(dev {np.max(np.abs(Ww.T @ Ew @ Ww - Ew)):.1e})")
x0 = np.zeros(2 * Nw)
x0[2:8] = rng.normal(size=6)
x0[Nw + 2:Nw + 8] = rng.normal(size=6)
e0 = x0 @ Ew @ x0
xs = x0.copy()
devs = []
for m in range(12):
    xs = Ww @ xs
    devs.append(abs(xs @ Ew @ xs - e0))
check(max(devs) < 1e-9 * max(1.0, abs(e0)),
      f"T1(a) E conserved along 12 steps of the wave evolution (E = {f6(e0)}, max drift "
      f"{max(devs):.1e})")
B = np.zeros(Lw + 2)
B[10:15] = rng.normal(size=5)
u = np.zeros(Nw)
v = np.zeros(Nw)
for k in range(1, Lw + 1):
    u[nw + k - 1] = B[k]
    v[nw + k - 1] = B[k + 1] if k + 1 <= Lw + 1 else 0.0
x = np.concatenate([u, v])
okd = True
for m in range(1, 8):
    x = Ww @ x
    pred = np.zeros(Nw)
    for k in range(1, Lw + 1):
        kk = k - m
        pred[nw + k - 1] = B[kk] if 1 <= kk < len(B) else 0.0
    okd = okd and np.max(np.abs(x[:Nw] - pred)) < 1e-10
check(okd, "T1(a) d'Alembert on the ray: purely outgoing data u_m(k) = B(k - m) propagates "
           "with speed one and never reaches the core (8 steps)")
supp_ok = True
xx = np.zeros(2 * Nw)
xx[nw + 29] = 1.0
xx[Nw + nw + 29] = 1.0
for m in range(1, 9):
    xx = Ww @ xx
    idx = np.where(np.abs(xx) > 1e-12)[0]
    lo = min([i for i in idx if i < Nw] + [i - Nw for i in idx if i >= Nw])
    supp_ok = supp_ok and lo >= nw + 29 - m - 1
check(supp_ok, "T1(a) finite propagation speed one: data at r_30 stays beyond r_{30-m-1} "
               "after m steps, so a truncated ray is exact for a bounded number of steps")
inv_b = max(np.max(np.abs(Ww @ bvec_w(j) - bvec_w(j + 1))) for j in range(1, 20))
Wi = np.linalg.inv(Ww)
inv_f = max(np.max(np.abs(Wi @ fvec_w(j) - fvec_w(j + 1))) for j in range(1, 20))
check(inv_b < 1e-12 and inv_f < 1e-12,
      f"T1(a) W b_j = b_{{j+1}} and W^-1 f_j = f_{{j+1}} exactly (dev {inv_b:.1e}, "
      f"{inv_f:.1e}): D_+ is W-invariant, D_- is W^-1-invariant, each with a ONE-dimensional "
      f"wandering vector -- the one-dimensional exit")

print("\n-- D_+ must start at b_2: the brief's D_+ is not E-orthogonal to D_-")
for TXt, ct, tag in [(TXw, cw, "2-vertex core c=1.1"),
                     (np.array([[0.0]]), np.sqrt(3.0), "pure cusp q=2"),
                     (np.array([[1.0]]), np.sqrt(0.5), "loop a=1 c^2=0.5")]:
    nt, Nt, Tt, Et, Wt, bt, ft = lp_pieces(TXt, ct, 40)
    v11 = bt(1) @ Et @ ft(1)
    worst = max(abs(bt(j) @ Et @ ft(k)) for j in range(2, 12) for k in range(1, 12))
    check(abs(v11 - (1 - ct * ct) / 2) < 1e-12 and worst < 1e-12,
          f"{tag}: <b_1, E f_1> = (1 - c^2)/2 = {f6(v11)} is NONZERO unless c = 1, while "
          f"<b_j, E f_k> = 0 for all j >= 2 (worst {worst:.1e}); so the outgoing space is "
          f"D_+ = span{{b_j : j >= 2}}, i.e. B supported on k >= 2")

print("\n-- the two threshold modes: finite energy, not in l^2")
for tag, TXt, ct in [("pure cusp q=2", np.zeros((1, 1)), np.sqrt(3.0)),
                     ("loop a=1 c^2=0.5", np.array([[1.0]]), np.sqrt(0.5))]:
    nt, Nt, Tt, Et, Wt, bt, ft = lp_pieces(TXt, ct, 60)
    for name, sgn in (("constant (z = +1)", 1.0), ("alternating (z = -1)", -1.0)):
        for P in (20, 30):
            t = np.zeros(2 * Nt)
            for k in range(P, 55):
                t[nt + k - 1] = sgn ** k
                t[Nt + nt + k - 1] = sgn * sgn ** k if sgn > 0 else -(sgn ** k)
            en = t @ Et @ t
            nrm = np.linalg.norm(t) ** 2
            check(abs(en - 2.0) < 1e-10,
                  f"{tag}: the {name} tail on r_{P}..r_54 has E = {f6(en)} = 2 independent of "
                  f"its length, while ||.||^2 = {f6(nrm)} grows: E-finite, not l^2 "
                  f"(E is degenerate at lambda = +-2)")

print("\n-- trivial eigen-data spans an E-hyperbolic plane (two E-null directions)")
for tag, TXt, ct in [("pure cusp q=2", np.zeros((1, 1)), np.sqrt(3.0)),
                     ("loop a=1 c^2=4", np.array([[1.0]]), 2.0),
                     ("K4, q=2, c^2=3", regular_TX(K4, 2), np.sqrt(3.0))]:
    sd = spectrum_data(TXt, ct)
    nt, Nt, Tt, Et, Wt, bt, ft = lp_pieces(TXt, ct, 200)
    for lam, psi in l2_eigvecs(TXt, ct, 200):
        if abs(lam) <= 2 + 1e-9:
            continue
        z = (lam - np.sign(lam) * np.sqrt(lam * lam - 4)) / 2
        d1 = np.concatenate([psi, psi / z])
        d2 = np.concatenate([psi, psi * z])
        q1 = d1 @ Et @ d1
        q2 = d2 @ Et @ d2
        sig = np.linalg.eigvalsh(np.array([[1.0, -lam / 2], [-lam / 2, 1.0]]))
        check(abs(q1) < 1e-8 and abs(q2) < 1e-8 and sig.min() < 0 < sig.max(),
              f"{tag}: for the trivial mode lambda = {f6(lam)} (z = {f6(z)}), both W-eigen-data "
              f"(psi, psi/z) and (psi, z psi) are E-NULL ({q1:.1e}, {q2:.1e}); E on the plane "
              f"has signature (1 - lam/2, 1 + lam/2) = ({f6(sig[1])}, {f6(sig[0])}), indefinite")

print("\n-- dim K from the D_+/D_- construction, and by how much it misses #resonances")
print("   core                          n  #res  mu  t_nc  beta | dimK_c  2(n-mu-t_nc)-2")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    n = sd["n"]
    mu = len(sd["cusp"])
    tnc = len(sd["triv_nc"])
    beta = sd["n_edge"]
    nres = len(sd["res"])
    d1 = K_compact(TX, c, M=8)
    d2 = K_compact(TX, c, M=12)
    pred = max(0, 2 * (n - mu - tnc) - 2)
    print(f"   {tag:28s} {n:2d} {nres:5d} {mu:3d} {tnc:5d} {beta:5d} | {d1:6d} {pred:15d}")
    check(d1 == pred == d2,
          f"{tag}: dim K (compactly supported) = {d1} = max(0, 2(n - mu - t_nc) - 2), stable "
          f"in the ray cut (M = 8 and M = 12); each l^2 eigen-datum removes 2")
    check(d1 == max(0, nres - tnc + beta - 2),
          f"{tag}: equivalently dim K = #res - t_nc + beta - 2 (clipped at 0): the brief's "
          f"'dim K = #resonances' misses t_nc + 2 - beta dimensions")
    check(K_compact(TX, c, M=8, jstart=1) <= d1,
          f"{tag}: keeping the brief's b_1 in D_+ removes still more "
          f"({K_compact(TX, c, M=8, jstart=1)} left)")
flag("T1(c) CORRECTED: with D_+ = span{b_j, j >= 2}, D_- = span{f_j, j >= 1} and H_LP the "
     "E-orthocomplement of ALL l^2 eigen-data, the l^2 space K has dimension "
     "2(n - mu - t_nc) - 2 = #res - t_nc - 2 (beta = 0), not #res. The deficit is exactly the "
     "2 threshold modes at z = +-1 (E-finite, not l^2) plus one E-isotropic direction per "
     "trivial mode (its eigen-data plane is E-hyperbolic, so removing all of it over-counts). "
     "The energy completion, not l^2, is the right space; verified on 19 cores.")

print("\n-- the functional model of Z built from the graph's resonances")
MODELS = {}
RENEW = [("loop a=1.0 c^2=0.5", np.array([[1.0]]), np.sqrt(0.5)),
         ("loop a=0.5 c^2=1.2", np.array([[0.5]]), np.sqrt(1.2)),
         ("K4, q=2, c^2=3", regular_TX(K4, 2), np.sqrt(3.0)),
         ("random 3-vertex core #2", CORES[14][1], CORES[14][2])]
for tag, TX, c in RENEW:
    sd = spectrum_data(TX, c)
    res = sortc(sd["res"])
    mdl = gram_model(res)
    mdl["res"] = res
    MODELS[tag] = mdl
    print(f"   {tag}: {mdl['d']} resonances {clist(res)}, Gram cond {mdl['cond']:.3f}")

for tag in MODELS:
    m = MODELS[tag]
    C, jj, d, V, zs = m["C"], m["j"], m["d"], m["V"], m["z"]
    check(np.max(np.abs(np.linalg.eigvals(C) - np.array(sortc(np.linalg.eigvals(C))))) >= 0
          and max(abs(a - b) for a, b in zip(sortc(np.linalg.eigvals(C)), sortc(zs))) < 1e-9,
          f"T1(c) {tag}: spec Z = the resonances THEMSELVES, all in |z| < 1 "
          f"(max |z| = {max(abs(zs)):.6f}); the reflections 1/conj z lie outside the disc "
          f"and cannot be the spectrum of a contraction")
    dz = np.eye(d) - C.conj().T @ C
    dzs = np.eye(d) - C @ C.conj().T
    sv = np.linalg.svd(dz, compute_uv=False)
    sv2 = np.linalg.svd(dzs, compute_uv=False)
    check(np.max(np.abs(dz - np.outer(jj, jj.conj()))) < 1e-9
          and (len(sv) == 1 or sv[1] < 1e-9 * sv[0]),
          f"T1(c) {tag}: 1 - Z^*Z = |j><j| is rank one with j = G^(-1/2) 1 "
          f"(dev {np.max(np.abs(dz - np.outer(jj, jj.conj()))):.1e})")
    check(len(sv2) == 1 or sv2[1] < 1e-8 * sv2[0],
          f"T1(c) {tag}: 1 - Z Z^* is rank one too (both defect indices are 1)")
    mfar = int(np.ceil(np.log(1e-8) / np.log(max(abs(zs))))) + 4 * d
    nrm = [np.linalg.norm(np.linalg.matrix_power(C, mm), 2) for mm in (1, 4, 12, mfar)]
    check(nrm[0] <= 1 + 1e-9 and nrm[-1] < 1e-3,
          f"T1(c) {tag}: Z is a contraction and Z^m -> 0 (||Z^m|| at m = 1, 4, 12, {mfar} = "
          f"{', '.join(f'{x:.3e}' for x in nrm)})")
    alph = np.array([jj.conj() @ V[:, i] for i in range(d)])
    Gr = V.conj().T @ V
    pred = np.outer(alph.conj(), alph) / (1 - np.outer(zs.conj(), np.ones(d))
                                          * np.outer(np.ones(d), zs))
    check(np.max(np.abs(Gr - pred)) < 1e-9 and np.min(np.abs(alph)) > 1e-8,
          f"T1(c) {tag}: <k_n,k_m> = conj(a_n) a_m/(1 - conj(z_n) z_m) with a_n = <j|k_n> = 1 "
          f"(dev {np.max(np.abs(Gr - pred)):.1e}); a_n != 0 for every mode, so NO resonance "
          f"mode is decoupled from the cusp (the brief's guess 1/(1 - z_n conj z_m) is right "
          f"up to this normalisation)")
    dev = 0.0
    for w in (0.3, -0.55, 0.4j, 0.2 + 0.6j):
        th = char_fn(C, jj, w)
        bl = blaschke(zs, w)
        dev = max(dev, abs(abs(th) - abs(bl)))
    check(dev < 1e-9,
          f"T1(d) {tag}: |characteristic function of Z| = |Blaschke product over the "
          f"resonances| (dev {dev:.1e}); and by C2 that Blaschke product is R times the "
          f"Blaschke product of the trivial modes -- NOT R and NOT 1/R")

ZF = np.array([[0.0, 1.0], [0.0, 0.0]])
JF = np.array([1.0, 0.0])
check(np.max(np.abs(np.eye(2) - ZF.T @ ZF - np.outer(JF, JF))) < 1e-14
      and len(spectrum_data(np.zeros((1, 1)), 1.0)["res"]) == 2
      and max(abs(z) for z in spectrum_data(np.zeros((1, 1)), 1.0)["res"]) < 1e-7,
      "T1(c) the FREE half line (T_X = [0], c = 1) has p(z) = z^2, ptilde = 1, R = -z^2 and a "
      "DOUBLE resonance at z = 0; its model is the 2x2 nilpotent Jordan block, the one case "
      "where H-SIMPLE fails")

# ================================================================ T3-T5
print("\n" + "=" * 78)
print("T3-T5  the renewal channel in discrete time")
print("=" * 78)

for tag in MODELS:
    m = MODELS[tag]
    C, jj, d = m["C"], m["j"], m["d"]
    Om = rand_density(d, rng)
    pv, ov = np.linalg.eigh(Om)
    kraus = [C] + [np.sqrt(max(pv[i], 0.0)) * np.outer(ov[:, i], jj.conj()) for i in range(d)]
    ssum = sum(k.conj().T @ k for k in kraus)
    check(np.max(np.abs(ssum - np.eye(d))) < 1e-10,
          f"T3(a) {tag}: Kraus set {{C, sqrt(p_i)|w_i><j|}} is trace preserving, "
          f"sum K^*K = 1 (dev {np.max(np.abs(ssum - np.eye(d))):.1e})")
    choi = sum(np.kron(k, k.conj()) for k in kraus)
    Lm = superop(C, Om, jj)
    check(np.max(np.abs(Lm - (np.kron(C, C.conj())
                              + np.outer(Om.reshape(-1),
                                         np.outer(jj, jj.conj()).T.reshape(-1))))) < 1e-12,
          f"T3(a) {tag}: the superoperator matches the Kraus channel on random densities")
    r0 = rand_density(d, rng)
    check(np.max(np.abs((Lm @ r0.reshape(-1)).reshape(d, d) - apply_E(C, Om, jj, r0))) < 1e-11,
          f"T3(a) {tag}: row-major vec of E_Omega reproduces C rho C^* + <j|rho|j> Omega")
    cj = np.zeros((d * d, d * d), dtype=complex)
    for k in kraus:
        cj += np.outer(k.reshape(-1), k.reshape(-1).conj())
    check(np.linalg.eigvalsh(cj).min() > -1e-10,
          f"T3(a) {tag}: Choi matrix is positive semidefinite (min eig "
          f"{np.linalg.eigvalsh(cj).min():.1e}) -- E_Omega is CPTP")
    MM = 4000
    tm = [1.0]
    Y = Om.copy()
    law = []
    for mm in range(1, MM + 1):
        law.append((jj.conj() @ Y @ jj).real)
        Y = C @ Y @ C.conj().T
        tm.append(np.trace(Y).real)
    law = np.array(law)
    check(min(law) > -1e-14 and abs(law.sum() - (1 - tm[MM])) < 1e-12 and tm[MM] < 1e-6,
          f"T3(b) {tag}: m(m) = <j|C^(m-1) Omega C^*(m-1)|j> >= 0 and telescopes exactly, "
          f"sum_1^M m(m) = 1 - Tr(C^M Omega C^*M) = {f6(law.sum())} -> 1 "
          f"(Tr(C^M ...) = {tm[MM]:.1e})")
    X = stein(C, Om)
    mu = np.trace(X).real
    mean = float(np.sum(np.arange(1, MM + 1) * law))
    check(abs(mean - mu) < 1e-6 * mu,
          f"T3(b) {tag}: mean holding time {f6(mean)} = sum_m Tr(C^m Omega C^*m) = Tr X with "
          f"X - C X C^* = Omega, = {f6(mu)} < infinity (finite dimension: the infinite-mean "
          f"phenomenon of 04h cannot occur)")
    rinf = X / mu
    check(np.max(np.abs(apply_E(C, Om, jj, rinf) - rinf)) < 1e-10,
          f"T3(c) {tag}: rho_inf = mu^-1 sum_m C^m Omega C^*m is stationary (dev "
          f"{np.max(np.abs(apply_E(C, Om, jj, rinf) - rinf)):.1e})")
    w, Vv = np.linalg.eig(Lm)
    i1 = int(np.argmin(np.abs(w - 1)))
    rn = Vv[:, i1].reshape(d, d)
    rn = 0.5 * (rn + rn.conj().T)
    rn = rn / np.trace(rn).real
    check(np.max(np.abs(rn - rinf)) < 1e-8,
          f"T3(c) {tag}: the null vector of 1 - E_Omega agrees with the renewal sum "
          f"(dev {np.max(np.abs(rn - rinf)):.1e})")
    rest = np.sort(np.abs(np.delete(w, i1)))[::-1]
    check(abs(abs(w[i1]) - 1) < 1e-9 and rest[0] < 1 - 1e-6,
          f"T3(c) {tag}: eigenvalue 1 of E_Omega is simple and all others have modulus "
          f"<= {rest[0]:.6f} < 1, so rho_inf is unique and attracting (aperiodic case)")
    rr = rand_density(d, rng)
    for _ in range(4000):
        rr = apply_E(C, Om, jj, rr)
    check(np.max(np.abs(rr - rinf)) < 1e-6,
          f"T3(c) {tag}: 4000 iterations from a random density converge to rho_inf "
          f"(dev {np.max(np.abs(rr - rinf)):.1e})")
    for u in (0.3, 0.61, -0.45, 0.8j):
        E0 = np.kron(C, C.conj())
        mh = mhat(C, Om, jj, u)
        lhs = np.linalg.det(np.eye(d * d) - u * Lm)
        rhs = np.linalg.det(np.eye(d * d) - u * E0) * (1 - mh)
        check(abs(lhs - rhs) < 1e-8 * max(1.0, abs(lhs)),
              f"T3(e) {tag}: det(1 - u E_Omega) = det(1 - u E_0)(1 - mhat(u)) at u = {c6(u)} "
              f"(|lhs - rhs| = {abs(lhs - rhs):.1e})")
    # purity criterion
    kv = m["V"][:, 0]
    kv = kv / np.linalg.norm(kv)
    Omp = np.outer(kv, kv.conj())
    rp_ = stein(C, Omp)
    rp_ = rp_ / np.trace(rp_).real
    psi2 = rng.normal(size=d) + 1j * rng.normal(size=d)
    psi2 /= np.linalg.norm(psi2)
    Omq = np.outer(psi2, psi2.conj())
    rq = stein(C, Omq)
    rq = rq / np.trace(rq).real
    check(abs(np.trace(rp_ @ rp_).real - 1) < 1e-9 and np.trace(rq @ rq).real < 1 - 1e-6,
          f"T3(d) {tag}: rho_inf is PURE iff Omega is a pure state that is an EIGENVECTOR of C "
          f"(purity {f6(np.trace(rp_ @ rp_).real)}); a generic pure Omega gives purity "
          f"{f6(np.trace(rq @ rq).real)} < 1")

# periodic counterexample from a real graph: the free half line, Z nilpotent
Zf = np.array([[0.0, 1.0], [0.0, 0.0]])
df = 2
jf = np.array([1.0, 0.0])
check(np.max(np.abs(np.eye(2) - Zf.T @ Zf - np.outer(jf, jf))) < 1e-14
      and np.max(np.abs(Zf @ Zf)) < 1e-14,
      f"T3(c) periodic counterexample: the FREE half line (T_X = [0], c = 1) has p(z) = z^2, "
      f"ptilde = 1, two resonances at z = 0, and its model contraction is the 2x2 nilpotent "
      f"Jordan block with 1 - Z^*Z = |e_1><e_1|")
pv, ov = np.linalg.eigh(np.eye(df) - np.outer(jf, jf.conj()))
psi_perp = ov[:, -1]
Omp2 = np.outer(psi_perp, psi_perp.conj())
lawp = np.array([jf.conj() @ np.linalg.matrix_power(Zf, mm - 1) @ Omp2
                 @ np.linalg.matrix_power(Zf.conj().T, mm - 1) @ jf for mm in range(1, 6)]).real
Lp = superop(Zf, Omp2, jf)
wp = np.linalg.eigvals(Lp)
check(abs(lawp[0]) < 1e-12 and abs(lawp[1] - 1) < 1e-9
      and min(abs(wp + 1)) < 1e-9,
      f"T3(c) {'periodic'}: with Omega = |psi><psi|, psi perp j, the holding law is "
      f"{flist_raw(lawp)} (m = 1..5) -- supported on {{2}}, period 2; E_Omega has the eigenvalue -1 "
      f"(min |w + 1| = {min(abs(wp + 1)):.1e}), so the stationary state is not attracting")
for tag in MODELS:
    m = MODELS[tag]
    C, jj, d = m["C"], m["j"], m["d"]
    kv = m["V"][:, 0] / np.linalg.norm(m["V"][:, 0])
    z0 = m["z"][0]
    Omk = np.outer(kv, kv.conj())
    lawk = np.array([jj.conj() @ np.linalg.matrix_power(C, mm - 1) @ Omk
                     @ np.linalg.matrix_power(C.conj().T, mm - 1) @ jj
                     for mm in range(1, 8)]).real
    check(np.min(lawk) > 1e-12,
          f"T3(c) {tag}: for Omega on a single resonance z = {c6(z0)}, the holding law is "
          f"m(m) = |<j|k>|^2 |z|^(2m-2) > 0 for EVERY m, so gcd = 1: aperiodicity needs only "
          f"z != 0, not that the resonance is non-real")

print("\n-- T4  mode-diagonal rebounds and the uniform-modulus criterion")
for tag in MODELS:
    m = MODELS[tag]
    C, jj, d, V, zs = m["C"], m["j"], m["d"], m["V"], m["z"]
    Vh = V / np.linalg.norm(V, axis=0)
    pvec = rng.random(d)
    pvec = pvec / pvec.sum()
    Om = sum(pvec[i] * np.outer(Vh[:, i], Vh[:, i].conj()) for i in range(d))
    tm = [np.trace(np.linalg.matrix_power(C, mm) @ Om
                   @ np.linalg.matrix_power(C.conj().T, mm)).real for mm in range(500)]
    mu_pred = float(np.sum(pvec / (1 - np.abs(zs) ** 2)))
    check(abs(sum(tm) - mu_pred) < 1e-6,
          f"T4 {tag}: mu_Omega = sum_i p_i/(1 - |z_i|^2) = {f6(mu_pred)} = {f6(sum(tm))} "
          f"(direct sum)")
    Xs = sum(np.linalg.matrix_power(C, mm) @ Om @ np.linalg.matrix_power(C.conj().T, mm)
             for mm in range(500))
    rinf = Xs / np.trace(Xs).real
    mods = np.abs(zs)
    uniform = (mods.max() - mods.min()) < 1e-9
    dev = np.max(np.abs(rinf - Om))
    check((dev < 1e-7) == uniform,
          f"T4 {tag}: |z_i| = {flist(mods)}; uniform modulus = {uniform}, and "
          f"rho_inf = Omega is {dev < 1e-7} (||rho_inf - Omega|| = {dev:.1e})")
    if uniform:
        r = mods[0]
        check(abs(sum(tm) - 1 / (1 - r * r)) < 1e-6,
              f"T4 {tag}: under uniform modulus r = {f6(r)} the mean holding time is "
              f"1/(1 - r^2) = {f6(1/(1-r*r))}, independent of the mixture")
    spec = np.sort(np.linalg.eigvalsh(rinf))[::-1]
    check(np.max(np.abs(spec - np.sort(pvec)[::-1])) > 1e-4 or d == 1,
          f"T4 {tag}: the spectrum of rho_inf is {flist(spec)}, NOT the weight list "
          f"{flist(pvec)} -- a Gram spectrum, because the k_i are not orthogonal "
          f"(max |<k_i,k_j>| off-diagonal "
          f"{np.max(np.abs(Vh.conj().T @ Vh - np.eye(d))):.4f})")

print("\n-- T5  admissibility and invariant flags")
for tag in MODELS:
    m = MODELS[tag]
    C, jj, d, V, zs = m["C"], m["j"], m["d"], m["V"], m["z"]
    sig = rand_density(d, rng)
    Q = sig - C @ sig @ C.conj().T
    check(abs(np.trace(Q).real - (jj.conj() @ sig @ jj).real) < 1e-11,
          f"T5 {tag}: Tr Q_sigma = <j|sigma|j> = {f6((jj.conj() @ sig @ jj).real)} for a random "
          f"density (dev {abs(np.trace(Q).real - (jj.conj() @ sig @ jj).real):.1e})")
    if np.linalg.eigvalsh(Q).min() > 1e-12:
        Om2 = Q / np.trace(Q).real
        check(np.max(np.abs(apply_E(C, Om2, jj, sig) - sig)) < 1e-10,
              f"T5 {tag}: Q_sigma >= 0, so sigma is stationary for Omega = Q/Tr Q "
              f"(dev {np.max(np.abs(apply_E(C, Om2, jj, sig) - sig)):.1e})")
    else:
        flag(f"T5 {tag}: a random density had Q_sigma with a negative eigenvalue "
             f"({np.linalg.eigvalsh(Q).min():.3e}) -- admissibility is a real restriction")
    order = np.argsort(-np.abs(zs))
    Vs = V[:, order]
    pk = np.sort(rng.random(d))[::-1]
    pk = pk / pk.sum()
    Ps = []
    for k in range(1, d + 1):
        Qm, _ = np.linalg.qr(Vs[:, :k])
        Ps.append(Qm @ Qm.conj().T)
    sigf = sum((pk[k] - (pk[k + 1] if k + 1 < d else 0.0)) * Ps[k] for k in range(d))
    qs = [Ps[k] - C @ Ps[k] @ C.conj().T for k in range(d)]
    check(all(np.linalg.eigvalsh(q).min() > -1e-10 for q in qs),
          f"T5 {tag}: for the C-invariant flag of resonance eigenvectors, every "
          f"Q_k = P_k - C P_k C^* >= 0 (min eig "
          f"{min(np.linalg.eigvalsh(q).min() for q in qs):.1e})")
    spec = np.sort(np.linalg.eigvalsh(sigf))[::-1]
    Qf = sigf - C @ sigf @ C.conj().T
    check(np.max(np.abs(spec - pk)) < 1e-9 and np.linalg.eigvalsh(Qf).min() > -1e-10,
          f"T5 {tag}: sigma = sum (p_k - p_k+1) P_k is admissible and has the PRESCRIBED "
          f"spectrum {flist(pk)} (dev {np.max(np.abs(spec - pk)):.1e})")
    Omf = Qf / np.trace(Qf).real
    check(np.max(np.abs(apply_E(C, Omf, jj, sigf) - sigf)) < 1e-10,
          f"T5 {tag}: and it is the stationary state of its own renewal channel")
    # Schur form in the resonance basis
    Sc = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))
    Sc = Sc @ Sc.conj().T
    sig2 = V @ Sc @ V.conj().T
    Q2 = sig2 - C @ sig2 @ C.conj().T
    coef = Sc * (1 - np.outer(zs, zs.conj()))
    check(np.max(np.abs(Q2 - V @ coef @ V.conj().T)) < 1e-9,
          f"T5 {tag}: in the resonance basis Q_sigma has coefficient matrix "
          f"sigma_nm (1 - z_n conj z_m) -- an entrywise (Schur) factor, dev "
          f"{np.max(np.abs(Q2 - V @ coef @ V.conj().T)):.1e}")

# ================================================================ T6
print("\n" + "=" * 78)
print("T6  the graded space: odd coherences are eigen-operators")
print("=" * 78)
for tag in MODELS:
    m = MODELS[tag]
    C, jj, d, V, zs = m["C"], m["j"], m["d"], m["V"], m["z"]
    Ct = np.zeros((d + 1, d + 1), dtype=complex)
    Ct[0, 0] = 1.0
    Ct[1:, 1:] = C
    jt = np.zeros(d + 1, dtype=complex)
    jt[1:] = jj
    check(np.max(np.abs(np.eye(d + 1) - Ct.conj().T @ Ct - np.outer(jt, jt.conj()))) < 1e-10,
          f"T6 {tag}: on C vac (+) K with C vac = vac, 1 - C^*C = |j><j| still holds "
          f"(the vacuum has no exit)")
    for trial in range(3):
        Omt = rand_density(d + 1, rng)
        for i in range(d):
            ki = np.zeros(d + 1, dtype=complex)
            ki[1:] = V[:, i] / np.linalg.norm(V[:, i])
            vac = np.zeros(d + 1, dtype=complex)
            vac[0] = 1.0
            Aop = np.outer(ki, vac.conj())
            out = Ct @ Aop @ Ct.conj().T + (jt.conj() @ Aop @ jt) * Omt
            check(np.max(np.abs(out - zs[i] * Aop)) < 1e-10,
                  f"T6 {tag} rebound #{trial+1}: |k_{i}><vac| is an eigen-operator with "
                  f"eigenvalue z_{i} = {c6(zs[i])} (NOT conj z), because the exit functional "
                  f"annihilates odd operators (dev "
                  f"{np.max(np.abs(out - zs[i] * Aop)):.1e})")

# ================================================================ T7
print("\n" + "=" * 78)
print("T7  RAM(Y) and RH(Y): independence, and what pins the modulus")
print("=" * 78)


def ram_rh(TX, c):
    sd = spectrum_data(TX, c)
    lam = sd["triv_lam"]
    if len(lam) == 0:
        ram = True
    else:
        top = max(abs(x) for x in lam)
        ram = len(lam) <= 2 and all(abs(abs(x) - top) < 1e-8 for x in lam) and \
            (len(lam) == 1 or abs(lam[0] + lam[-1]) < 1e-8)
    res = sd["res"]
    mods = sorted(abs(z) for z in res)
    rh = len(res) <= 1 or (mods[-1] - mods[0]) < 1e-6   # 1e-6: multiple roots of p
    return ram, rh, res, mods, lam, sd


rows = []
for a in (-3.0, -2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0, 3.0):
    for c2 in (0.25, 0.5, 0.75, 1.25, 1.5, 2.0, 3.0, 4.0, 6.0):
        TX = np.array([[a]])
        ram, rh, res, mods, lam, sd = ram_rh(TX, np.sqrt(c2))
        rows.append((a, c2, len(res), len(lam), ram, rh, mods, res))
combos = {}
for a, c2, nres, ntr, ram, rh, mods, res in rows:
    combos.setdefault((ram, rh), []).append((a, c2, nres, ntr, mods))
print("\n   one-vertex loop core, T_X = [a]:  (RAM, RH) -> count, first example")
for key in [(True, True), (True, False), (False, True), (False, False)]:
    v = combos.get(key, [])
    if v:
        a, c2, nres, ntr, mods = v[0]
        print(f"   RAM={str(key[0]):5s} RH={str(key[1]):5s}  {len(v):3d} of {len(rows)}   "
              f"e.g. a={f6(a)} c^2={f6(c2)}: {nres} resonances |z| = {flist(mods)}, "
              f"{ntr} trivial l^2")
    else:
        print(f"   RAM={str(key[0]):5s} RH={str(key[1]):5s}    0 of {len(rows)}   "
              f"(not realised by a one-vertex core)")
check(all(k in combos for k in [(True, True), (True, False), (False, True)]),
      "T7(a): a ONE-vertex loop core already realises RAM&RH, RAM&not-RH and not-RAM&RH, so "
      "RAM and RH are independent; neither implies the other")
check((False, False) not in combos,
      "T7(a): a one-vertex core can NEVER realise not-RAM & not-RH: #res + #trivial <= 2n = 2, "
      "and not-RAM needs 2 trivial while not-RH needs 2 resonances")

neither = []
for trial in range(400):
    k = int(rng.integers(2, 4))
    A = np.round(rng.normal(size=(k, k)) * 1.2, 3)
    A = 0.5 * (A + A.T)
    c = float(np.round(0.4 + 1.6 * rng.random(), 3))
    ram, rh, res, mods, lam, sd = ram_rh(A, c)
    if (not ram) and (not rh):
        neither.append((k, A, c, mods, lam))
def bip_core(n1, n2, gen):
    """A bipartite core (v_0 in the first part): T on Y is then bipartite, so its
    spectrum and its resonance set are symmetric under lambda -> -lambda, z -> -z."""
    n = n1 + n2
    A = np.zeros((n, n))
    Bm = np.round(gen.normal(size=(n1, n2)), 3)
    A[:n1, n1:] = Bm
    A[n1:, :n1] = Bm.T
    return A


nonvac = {}
for trial in range(600):
    k = int(rng.integers(2, 5))
    A = np.round(rng.normal(size=(k, k)) * 1.2, 3)
    A = 0.5 * (A + A.T)
    c = float(np.round(0.3 + 2.2 * rng.random(), 3))
    ram, rh, res, mods, lam, sd = ram_rh(A, c)
    if len(res) >= 2 and len(lam) >= 2:
        nonvac.setdefault((ram, rh), ("generic", k, A, c, mods, lam))
for trial in range(600):
    n1 = int(rng.integers(1, 3))
    n2 = int(rng.integers(1, 4))
    A = bip_core(n1, n2, rng)
    c = float(np.round(0.3 + 2.2 * rng.random(), 3))
    ram, rh, res, mods, lam, sd = ram_rh(A, c)
    if len(res) >= 2 and len(lam) >= 2:
        nonvac.setdefault((ram, rh), ("bipartite", n1 + n2, A, c, mods, lam))
print("\n   non-vacuous cases (>= 2 resonances AND >= 2 trivial l^2 modes), random cores:")
for key in [(True, True), (True, False), (False, True), (False, False)]:
    if key in nonvac:
        kind, k, A, c, mods, lam = nonvac[key]
        print(f"   RAM={str(key[0]):5s} RH={str(key[1]):5s}  {kind:9s} n={k} c={f6(c)}  "
              f"|z_res| = {flist(mods)}  trivial lam = {flist(lam)}")
    else:
        print(f"   RAM={str(key[0]):5s} RH={str(key[1]):5s}  none found in 1200 random cores")
check(len(nonvac) >= 3 and (False, False) in nonvac and (False, True) in nonvac,
      f"T7(a) non-vacuously (>= 2 resonances AND >= 2 trivial modes): {len(nonvac)} of the 4 "
      f"combinations occur; RAM(Y) non-vacuously needs a bipartite core (the two trivial modes "
      f"must be exactly +-lambda_top), which random symmetric cores essentially never are")

check(len(neither) > 0,
      f"T7(a): RAM and RH both FAIL for {len(neither)} of 400 random 2-3 vertex cores; "
      f"smallest example n = {min(x[0] for x in neither)}")
k0, A0, c0, mods0, lam0 = sorted(neither, key=lambda x: x[0])[0]
print(f"\n   'neither' example: n = {k0}, c = {f6(c0)}, T_X =\n{np.array2string(A0)}")
print(f"     resonance moduli {flist(mods0)}; trivial l^2 eigenvalues {flist(lam0)}")

print("\n-- T7(d) smallest cores with a non-real resonance pair")
sd1 = spectrum_data(np.array([[1.0]]), np.sqrt(0.5))
check(len(sd1["res"]) == 2 and abs(sd1["res"][0].imag) > 1e-6
      and abs(abs(sd1["res"][0]) - abs(sd1["res"][1])) < 1e-12,
      f"T7(d): the SMALLEST core with a non-real resonance pair is n = 1: T_X = [1], c^2 = 1/2 "
      f"gives z = {clist(sd1['res'])}, a conjugate pair, |z| = {f6(abs(sd1['res'][0]))} "
      f"= sqrt(1 - c^2); it automatically satisfies RH(Y) (conjugate pairs have equal modulus)")
check(all(len(spectrum_data(np.array([[a]]), c)["res"]) == 0
          or all(abs(z.imag) < 1e-9 for z in spectrum_data(np.array([[a]]), c)["res"])
          for a in (-2.0, -1.0, 0.0, 1.0, 2.0) for c in (np.sqrt(1.2), np.sqrt(2.0),
                                                         np.sqrt(3.0), 2.0)),
      "T7(d): for n = 1 a non-real pair requires a^2 < 4(1 - c^2), hence c^2 < 1; with the "
      "arithmetic junction c^2 = q + 1 > 1 a one-vertex core has only REAL resonances")
nonreal_rh = []
for trial in range(400):
    k = int(rng.integers(2, 4))
    A = np.round(rng.normal(size=(k, k)) * 1.2, 3)
    A = 0.5 * (A + A.T)
    c = float(np.round(1.0 + 1.0 * rng.random(), 3))
    ram, rh, res, mods, lam, sd = ram_rh(A, c)
    if rh and any(abs(z.imag) > 1e-7 for z in res) and len(res) >= 2:
        nonreal_rh.append((k, A, c, res))
check(len(nonreal_rh) > 0,
      f"T7(d): RH(Y) together with a non-real pair and c > 1 occurs for "
      f"{len(nonreal_rh)} of 400 random 2-3 vertex cores; smallest n = "
      f"{min(x[0] for x in nonreal_rh)} (a single conjugate pair is automatically RH)")

print("\n-- T7(b) the product identity and whether r is pinned")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    prod = np.prod(sd["rp"])
    check(abs(prod - (1 - c * c)) < 1e-8,
          f"{tag}: prod of ALL roots of p = {c6(prod)} = 1 - c^2 = {f6(1 - c*c)} exactly")
    P_in = float(np.prod([abs(z) for z in sd["rp"] if abs(z) < 1 - 1e-9])) if any(
        abs(z) < 1 - 1e-9 for z in sd["rp"]) else 1.0
    rhs = abs(1 - c * c) * float(np.prod([abs(z) for z in sd["triv_z"]])) if sd["triv_z"] \
        else abs(1 - c * c)
    check(abs(P_in - rhs) < 1e-7,
          f"{tag}: prod|roots of p inside| = |1 - c^2| * prod|trivial z| "
          f"({f6(P_in)} = {f6(rhs)}) -- this is the ONLY constraint on the resonance moduli")
check(abs(np.prod(spectrum_data(np.zeros((1, 1)), np.sqrt(3.0))["rp"]) + 2.0) < 1e-9,
      "T7(b): for the pure cusp |1 - c^2| = q and the trivial modes are +-q^-1/2, so the "
      "identity forces prod|resonances| = 1, impossible for moduli < 1 -- hence NO resonances; "
      "with c^2 = q+1 and only the Perron pair trivial, resonances cannot exist at all")
flag("T7(b): nothing pins r to q^-1/4. The product identity gives prod|res| = "
     "|1-c^2| prod|z_trivial|, so under RH(Y) with R resonances r^R is fixed by the TRIVIAL "
     "spectrum and c alone; r = q^-1/4 for all R would need |1-c^2| prod|z_t| = q^-R/4, a "
     "condition the arithmetic (extra trivial modes at deeper levels) must supply.")

print("\n-- T7(c) a checkable criterion: r-self-reciprocality of the reduced numerator")
for tag, TX, c in CORES:
    sd = spectrum_data(TX, c)
    res = sd["res"]
    if len(res) < 2:
        continue
    mods = np.array([abs(z) for z in res])
    rh = (mods.max() - mods.min()) < 1e-6
    r = float(mods.mean())
    if r < 1e-5:                                # all resonances at z = 0 (free half line)
        continue
    co = np.poly(np.array(res))[::-1]           # low-to-high, monic
    dg = len(co) - 1
    b = np.array([co[k] * r ** (k - dg) for k in range(dg + 1)])
    dev = np.max(np.abs(b - b[0] * b[::-1])) / max(1.0, np.max(np.abs(b)))
    check((dev < 1e-6) == rh,
          f"{tag}: RH(Y) = {rh} iff the reduced numerator, rescaled to b_k = c_k r^(k-d), is "
          f"self-reciprocal b_k = b_0 b_(d-k) with |b_0| = {abs(b[0]):.6f} "
          f"(deviation {dev:.1e}); moduli {flist(mods)}")

# ================================================================ summary
print("\n" + "=" * 78)
print(f"CHECKS PASSED: {CHECKS}")
print("=" * 78)
print(f"{len(FLAGS)} loud findings:")
for i, f in enumerate(FLAGS, 1):
    print(f"  ({i}) {f}")
