#!/usr/bin/env python3
"""50-digit (a_n, b_n) pins for a real primitive Dirichlet character, written INDEPENDENTLY.

This is a second, self-contained mpmath instance of the generic explicit-formula data model of
notes/zeta-spectral-triples/ellcurve/astra-review.md (F2, F3, F5, F6, F8, F13-F16).  It imports
nothing from ell_check.py, ccm_proto.py or the C library: everything below is transcribed from the
formula sheet directly, so that agreement with zst/src/dirichlet.c is a genuine cross-check of the
generic builder on a second L-function.

Data for the real primitive character chi_D of fundamental discriminant D (chi(n) = Kronecker (D/n)):
  atoms       w_{p,m} = -chi(p)^m log p p^{-m/2}   at y = m log p,   for all p^m <= X
              (chi(p^m) = chi(p)^m; chi(p) = 0 exactly at p | D)
  gamma       Gamma_R(s + kappa) = pi^{-(s+kappa)/2} Gamma((s+kappa)/2):
              Q = pi^{-1/2}, d = 2, mu = kappa + 1/2, multiplicity 1,
              kappa = 0 for D > 0 (even character), 1 for D < 0 (odd character)
  conductor   |D|                             poles   none (L(chi, s) is entire for chi non-principal)

Command (from notes/zeta-spectral-triples/ellcurve/checks/):

    python3 dirichlet_pins.py > ../../../../zst/tests/data/dirichlet_pins.txt
"""
import sys

from mpmath import mp

mp.dps = 70


def kronecker(D, p):
    """(D/p) for a PRIME p, from the definition (formula sheet, zst_weil_dirichlet contract)."""
    if p == 2:
        if D % 2 == 0:
            return 0
        return 1 if D % 8 in (1, 7) else -1
    r = D % p
    if r == 0:
        return 0
    return 1 if pow(r, (p - 1) // 2, p) == 1 else -1


def primes_upto(X):
    return [p for p in range(2, X + 1)
            if all(p % q for q in range(2, int(p ** 0.5) + 1))]


def rho(y, d, mu):
    return mp.exp(-mu * y) / (-mp.expm1(-d * y))


def I123(n, L, d, mu):
    """F13/F14 closed forms, with a generous series truncation."""
    w = 2 * mp.pi * n / L
    A = (mu - 1j * w) / d
    a = mu / d
    z = mp.exp(-d * L)
    e = mp.exp(-mu * L)
    K = int(mp.ceil((mp.dps + 15) * mp.log(10) / (d * L))) + 10
    S1 = S2 = mp.mpc(0)
    S10 = mp.mpf(0)
    zk = mp.mpf(1)
    for k in range(K):
        S1 += zk / (k + A)
        S2 += zk / (k + A) ** 2
        S10 += zk / (k + a)
        zk *= z
    I1 = -(mp.im(mp.digamma(A)) + e * mp.im(S1)) / d
    I2 = mp.re(mp.polygamma(1, A) - e * S2) / d ** 2 - e * L * mp.re(S1) / d
    I3 = (mp.digamma(a) - mp.re(mp.digamma(A)) - e * mp.re(S1) + e * S10) / d
    return I1, I2, I3


def tail(L, d, mu):
    """F8: T_{d,mu}(L) = int_L^inf rho, by quadrature (independent of the F13 series)."""
    return mp.quad(lambda u: rho(L + u, d, mu), [0, 1, 10, 50, mp.inf])


def build(D, X, N):
    L = mp.log(X)
    kappa = 0 if D > 0 else 1
    d, mu = mp.mpf(2), mp.mpf(kappa) + mp.mpf(1) / 2
    logQ = -mp.log(mp.pi) / 2                                    # Q = pi^{-1/2}
    # F8: s = log C + 2 log Q + (2/d) psi(mu/d) + 2 T_{d,mu}(L)
    shift = mp.log(abs(D)) + 2 * logQ + 2 * mp.digamma(mu / d) / d + 2 * tail(L, d, mu)
    atoms = []
    for p in primes_upto(X):
        c = kronecker(D, p)
        m, pm = 1, p
        while pm <= X:
            atoms.append((m * mp.log(p), -mp.mpf(c) ** m * mp.log(p) / mp.sqrt(pm), p, m, c))
            m += 1
            pm *= p
    a, b = [], []
    for n in range(N + 1):
        w = 2 * mp.pi * n / L
        I1, I2, I3 = I123(n, L, d, mu)
        a.append(-2 * (I3 - I2 / L) + shift
                 + 2 * sum(wt * (1 - y / L) * mp.cos(w * y) for y, wt, *_ in atoms))
        b.append(I1 / mp.pi - sum(wt * mp.sin(w * y) for y, wt, *_ in atoms) / mp.pi)
    b[0] = mp.mpf(0)                                             # F3: b_0 = 0 exactly
    return L, a, b, atoms, shift


def main():
    out = sys.stdout
    out.write("# dirichlet_pins: 50-digit (a_n, b_n) of the Weil form of L(chi_D, s) for real\n")
    out.write("# primitive characters, from an INDEPENDENT mpmath transcription of the formula\n")
    out.write("# sheet notes/zeta-spectral-triples/ellcurve/astra-review.md (F2/F5/F6/F8/F14/F16).\n")
    out.write("# generated by .../checks/dirichlet_pins.py:\n")
    out.write("#   python3 dirichlet_pins.py > ../../../../zst/tests/data/dirichlet_pins.txt\n")
    out.write("# mpmath dps = %d.  NOT interval certificates.\n" % mp.dps)
    out.write("# 'chi D x X N' block header, then 'ab n a_n b_n' lines.\n")
    for D in [-4, -3, 5, 8, -8, 13]:
        X = 13
        N = 8
        L, a, b, atoms, shift = build(D, X, N)
        out.write("chi %d %d %d %d\n" % (D, X, X, N))
        out.write("# shift s = %s\n" % mp.nstr(shift, 30))
        out.write("# atoms (p, m, chi(p), weight): %s\n"
                  % "; ".join("%d %d %d %s" % (p, m, c, mp.nstr(wt, 20))
                              for y, wt, p, m, c in atoms))
        for n in range(N + 1):
            out.write("ab %d %s %s\n" % (n, mp.nstr(a[n], 50, strip_zeros=False),
                                         mp.nstr(b[n], 50, strip_zeros=False)))


if __name__ == "__main__":
    main()
