#!/usr/bin/env python3
"""50-digit (a_n, b_n) pins for an elliptic curve, from the review lane's independent prototype.

This script only calls ell_check.build(), which is the review's own mpmath instance of the formula
sheet (F4/F5 atoms, F9 shift, F14 window integrals, F16 assembly) and whose closed forms were
checked against direct quadrature of the defining distribution
(`python3 ell_check.py checks` -> formula_check.out).  Nothing here calls the C library.

Command (from notes/zeta-spectral-triples/ellcurve/checks/):

    python3 ell_pins.py 11a1 13 8 > ../../../../zst/tests/data/ell_pins_11a1_x13_N8.txt
"""
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from mpmath import mp

mp.dps = 70

import ell_check


def main():
    name = sys.argv[1] if len(sys.argv) > 1 else "11a1"
    X = int(sys.argv[2]) if len(sys.argv) > 2 else 13
    N = int(sys.argv[3]) if len(sys.argv) > 3 else 8
    L, a, b, pp, ref = ell_check.build(name, X, N)
    out = sys.stdout
    out.write("# ell_pins: 50-digit (a_n, b_n) of the Weil form of an elliptic curve L-function,\n")
    out.write("# from notes/zeta-spectral-triples/ellcurve/checks/ell_check.py (the review lane's\n")
    out.write("# independent mpmath prototype of the formula sheet F4/F5/F9/F14/F16).\n")
    out.write("# generated by .../checks/ell_pins.py:\n")
    out.write("#   python3 ell_pins.py %s %d %d > ../../../../zst/tests/data/ell_pins_%s_x%d_N%d.txt\n"
              % (name, X, N, name, X, N))
    out.write("# mpmath dps = %d.  NOT interval certificates.\n" % mp.dps)
    out.write("curve %s %s %d %d %d %d\n"
              % (name, ",".join(str(v) for v in ref["model"]), ref["conductor"], X, X, N))
    out.write("# atoms: p m t_m weight\n")
    for y, wt, p, m, raw in pp:
        out.write("# atom %d %d %d %s\n" % (p, m, raw, mp.nstr(wt, 25)))
    for n in range(N + 1):
        out.write("ab %d %s %s\n" % (n, mp.nstr(a[n], 50, strip_zeros=False),
                                     mp.nstr(b[n], 50, strip_zeros=False)))


if __name__ == "__main__":
    main()
