#!/usr/bin/env python3
"""50-digit quadrature pins for the window integrals I1, I2, I3 and the tail T of the
exponential-series kernel rho_{d,mu}(y) = e^{-mu y}/(1 - e^{-d y}) = sum_{k>=0} e^{-(dk+mu)y}.

Independent of the C code and of the closed forms F13-F15: everything below is direct
mpmath quadrature of the DEFINING integrals of the formula sheet
(notes/zeta-spectral-triples/ellcurve/astra-review.md, F6, F8, F14):

    I1(n) = int_0^L sin(omega_n y) rho(y) dy
    I2(n) = int_0^L y cos(omega_n y) rho(y) dy
    I3(n) = int_0^L (cos(omega_n y) - 1) rho(y) dy      (written as -2 sin^2(omega_n y/2) rho)
    T(L)  = int_L^infinity rho(y) dy
    omega_n = 2 pi n / L,   L = log(X).

Command (from notes/zeta-spectral-triples/ellcurve/checks/):

    python3 kernel_pins.py > ../../../../zst/tests/data/kernel_pins.txt
"""
import sys

from mpmath import mp

mp.dps = 80


def rho(y, d, mu):
    return mp.exp(-mu * y) / (-mp.expm1(-d * y))


def I123(n, L, d, mu):
    w = 2 * mp.pi * n / L
    I1 = mp.quad(lambda y: mp.sin(w * y) * rho(y, d, mu), [0, L])
    I2 = mp.quad(lambda y: y * mp.cos(w * y) * rho(y, d, mu), [0, L])
    I3 = mp.quad(lambda y: -2 * mp.sin(w * y / 2) ** 2 * rho(y, d, mu), [0, L])
    return I1, I2, I3


def tail(L, d, mu):
    # int_L^inf rho = int_0^inf rho(L + u) du, split to help the quadrature at large u.
    f = lambda u: rho(L + u, d, mu)
    return mp.quad(f, [0, 1, 10, 50, mp.inf])


def fmt(v):
    return mp.nstr(v, 50, strip_zeros=False)


def main():
    out = sys.stdout
    out.write("# kernel_pins: 50-digit mpmath quadrature of the defining integrals of rho_{d,mu}\n")
    out.write("# (astra-review.md formula sheet F6/F8/F14).  NOT interval certificates.\n")
    out.write("# generated by notes/zeta-spectral-triples/ellcurve/checks/kernel_pins.py:\n")
    out.write("#   python3 kernel_pins.py > ../../../../zst/tests/data/kernel_pins.txt\n")
    out.write("# mpmath %s, dps = %d\n" % (mp.__version__ if hasattr(mp, "__version__") else "1.3.0", mp.dps))
    out.write("# 'i123 d mu n X I1 I2 I3' with L = log X;  'tail d mu X T'\n")
    cases = [
        ("1", "1", mp.mpf(1), mp.mpf(1)),
        ("2", "0.5", mp.mpf(2), mp.mpf(1) / 2),
        ("2", "1", mp.mpf(2), mp.mpf(1)),
        ("2", "2", mp.mpf(2), mp.mpf(2)),
    ]
    for ds, mus, d, mu in cases:
        for X in [9, 13]:
            L = mp.log(X)
            for n in [0, 1, 3, 5]:
                I1, I2, I3 = I123(n, L, d, mu)
                out.write("i123 %s %s %d %d %s %s %s\n" % (ds, mus, n, X, fmt(I1), fmt(I2), fmt(I3)))
            out.write("tail %s %s %d %s\n" % (ds, mus, X, fmt(tail(L, d, mu))))


if __name__ == "__main__":
    main()
